using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using pr.common;
using pr.extn;
using pr.gfx;
using pr.gui;
using pr.maths;
using pr.util;
using pr.win32;

namespace LDraw
{
	public class Model :IDisposable
	{
		public Model(MainUI main_ui)
		{
			Owner        = main_ui;
			View3d       = new View3d();
			IncludePaths = new List<string>();
			ContextIds   = new List<Guid>();
			SavedViews   = new List<SavedView>();
			DragDrop     = new DragDrop();
			Scene        = new SceneUI(this);
			Log          = new LogUI(this);

			// Apply initial settings
			AutoRefreshSources = Settings.AutoRefresh;
		}
		public void Dispose()
		{
			Log = null;
			Scene = null;
			View3d = null;
		}

		/// <summary>The UI that created this model</summary>
		public MainUI Owner
		{
			get;
			private set;
		}

		/// <summary>App settings</summary>
		public Settings Settings
		{
			[DebuggerStepThrough] get { return Owner.Settings; }
		}

		/// <summary>A view3d context reference that lives for the lifetime of the application</summary>
		public View3d View3d
		{
			[DebuggerStepThrough] get { return m_view3d; }
			set
			{
				if (m_view3d == value) return;
				if (m_view3d != null)
				{
					Util.Dispose(ref m_error_cb_gbl);
					Util.Dispose(ref m_view3d);
				}
				m_view3d = value;
				if (m_view3d != null)
				{
					m_error_cb_gbl = m_view3d.PushGlobalErrorCB(ReportError);
				}
			}
		}
		private View3d m_view3d;
		private Scope m_error_cb_gbl;

		/// <summary>The 3d scene</summary>
		public SceneUI Scene
		{
			[DebuggerStepThrough] get { return m_scene; }
			private set
			{
				if (m_scene == value) return;
				Util.Dispose(ref m_scene);
				m_scene = value;
			}
		}
		private SceneUI m_scene;

		/// <summary>The error log</summary>
		public LogUI Log
		{
			[DebuggerStepThrough] get { return m_log; }
			private set
			{
				if (m_log == value) return;
				Util.Dispose(ref m_log);
				m_log = value;
			}
		}
		private LogUI m_log;

		/// <summary>The View3d scene</summary>
		public View3d.Window Window
		{
			[DebuggerStepThrough] get { return Scene?.Scene?.Window; }
		}

		/// <summary>The View3d scene camera</summary>
		public View3d.CameraControls Camera
		{
			[DebuggerStepThrough] get { return Scene.Scene.Camera; }
		}

		/// <summary>Application include paths</summary>
		public List<string> IncludePaths
		{
			[DebuggerStepThrough] get;
			private set;
		}

		/// <summary>Context Ids of loaded script sources</summary>
		public List<Guid> ContextIds
		{
			get;
			private set;
		}

		/// <summary>Saved camera positions</summary>
		public List<SavedView> SavedViews
		{
			get;
			private set;
		}

		/// <summary>Drag drop handler</summary>
		public DragDrop DragDrop
		{
			get { return m_dd; }
			private set
			{
				if (m_dd == value) return;
				if (m_dd != null)
				{
					m_dd.DoDrop -= HandleDrop;
				}
				m_dd = value;
				if (m_dd != null)
				{
					m_dd.DoDrop += HandleDrop;
				}
			}
		}
		private DragDrop m_dd;
		private bool HandleDrop(object sender, DragEventArgs args, DragDrop.EDrop mode)
		{
			// File drop only
			if (!args.Data.GetDataPresent(DataFormats.FileDrop))
				return false;

			// The drop filepaths
			var files = (string[])args.Data.GetData(DataFormats.FileDrop);
			var extns = new string[] { ".ldr", ".p3d", ".x" };
			if (!files.All(x => extns.Contains(Path_.Extn(x).ToLowerInvariant())))
				return false;

			// Set the drop effect to indicate what will happen if the item is dropped here
			// e.g. args.Effect = Ctrl is down ? DragDropEffects.Move : DragDropEffects.Copy;
			var shift_down = (args.KeyState & Win32.MK_SHIFT) != 0;
			args.Effect = shift_down ? DragDropEffects.Copy : DragDropEffects.Move;

			// 'mode' == 'DragDrop.EDrop.Drop' when the item is actually dropped
			if (mode == DragDrop.EDrop.Drop)
			{
				var add = shift_down;
				foreach (var file in files)
				{
					OpenFile(file, add, false);
					add = true;
				}
				Scene.AutoRange();
			}

			// Return true because dropping is allowed/supported by this handler
			return true;
		}

		/// <summary>Handler for errors generated by View3d</summary>
		public void ReportError(IntPtr ctx, string msg)
		{
			// MsgBox.Show(Owner, msg, "LDraw Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
			Log.AddErrorMessage(msg);
		}

		/// <summary>Add a file source</summary>
		public void OpenFile(string filepath, bool additional, bool auto_range = true)
		{
			// Load a source file and save the context id for that file
			var id = View3d.LoadScriptSource(filepath, additional, async:true, include_paths: IncludePaths.ToArray());
			ContextIds.Add(id);

			if (auto_range)
			{
				Scene.Populate();
				Scene.AutoRange();
			}
		}

		/// <summary>Reset the camera to view objects in the scene</summary>
		public void ResetView(View3d.ESceneBounds bounds)
		{
			var bb = Window.SceneBounds(bounds);
			Camera.ResetView(bb, Settings.Camera.ResetForward, Settings.Camera.ResetUp);
		}

		/// <summary>Set the camera looking in the direction of 'fwd'</summary>
		public void CamForwardAxis(v4 fwd)
		{
			var c2w   = Camera.O2W;
			var focus = Camera.FocusPoint;
			var cam   = focus - fwd * Camera.FocusDist;

			Settings.Camera.ResetForward = fwd;
			Settings.Camera.ResetUp      = v4.Perpendicular(fwd, Settings.Camera.ResetUp);
			Scene.Options.ResetUp        = Settings.Camera.ResetUp;
			Scene.Options.ResetForward   = Settings.Camera.ResetForward;

			Camera.SetPosition(cam, focus, Settings.Camera.ResetUp);
		}

		/// <summary>Align the camera to the given axis</summary>
		public void AlignCamera(v4 axis)
		{
			Camera.AlignAxis = axis;
			Settings.Camera.AlignAxis = axis;
			if (axis != v4.Zero)
			{
				Settings.Camera.ResetForward = v4.Perpendicular(axis, Settings.Camera.ResetForward);
				Settings.Camera.ResetUp      = axis;
				Scene.Options.ResetUp        = Settings.Camera.ResetUp;
				Scene.Options.ResetForward   = Settings.Camera.ResetForward;
			}
		}

		/// <summary>Save the current camera position and view</summary>
		public void SaveView()
		{
			// Prompt for a name
			using (var dlg = new PromptForm { Title = "View Name:", Value = "View{0}".Fmt(SavedViews.Count + 1) })
			{
				dlg.ValueCtrl.SelectAll();
				if (dlg.ShowDialog(Owner) != DialogResult.OK) return;
				SavedViews.Add(new SavedView(dlg.Value, Camera));
			}
		}

		/// <summary>Clear the scene</summary>
		public void ClearScene()
		{
			// Remove and delete all objects (excluding focus points, selection boxes, etc)
			foreach (var id in ContextIds)
				View3d.DeleteAllObjects(id);

			// Remove all script sources
			View3d.ClearScriptSources();

			// Reset the list script source objects
			ContextIds.Clear();
		}

		/// <summary>Add a demo scene to the scene</summary>
		public void CreateDemoScene()
		{
			ContextIds.Add(Window.CreateDemoScene());
		}

		/// <summary>Cycle through to the next fill mode</summary>
		public void CycleFillMode()
		{
			Scene.Options.FillMode = Enum<View3d.EFillMode>.Cycle(Scene.Options.FillMode);
		}

		/// <summary>Enable/Disable auto refreshing of script sources</summary>
		public bool AutoRefreshSources
		{
			get { return m_timer_refresh != null; }
			set
			{
				if (AutoRefreshSources == value) return;
				if (m_timer_refresh != null)
				{
					m_timer_refresh.Tick -= View3d.CheckForChangedSources;
					Util.Dispose(ref m_timer_refresh);
				}
				m_timer_refresh = value ? new Timer { Interval = 500, Enabled = true } : null;
				if (m_timer_refresh != null)
				{
					m_timer_refresh.Tick += View3d.CheckForChangedSources;
				}
			}
		}
		private Timer m_timer_refresh;

		public class SavedView
		{
			public SavedView(string name, View3d.CameraControls camera)
			{
				Name         = name;
				C2W          = camera.O2W;
				FocusDist    = camera.FocusDist;
				AlignAxis    = camera.AlignAxis;
				Aspect       = camera.Aspect;
				FovX         = camera.FovX;
				FovY         = camera.FovY;
				Orthographic = camera.Orthographic;
			}

			public string Name         { get; set; }
			public m4x4   C2W          { get; private set; }
			public float  FocusDist    { get; private set; }
			public v4     AlignAxis    { get; private set; }
			public float  Aspect       { get; private set; }
			public float  FovX         { get; private set; }
			public float  FovY         { get; private set; }
			public bool   Orthographic { get; private set; }

			public void Apply(View3d.CameraControls camera)
			{
				camera.FocusDist    = FocusDist;
				camera.AlignAxis    = AlignAxis;
				camera.Aspect       = Aspect;
				camera.FovX         = FovX;
				camera.FovY         = FovY;
				camera.Orthographic = Orthographic;
				camera.O2W          = C2W;
				camera.Commit();
			}
		}
	}
}
