//***************************************************************************************************
// Ldr Object
//  Copyright (c) Rylogic Ltd 2009
//***************************************************************************************************
//
// Template example syntax:
//   *Keyword [<name>] [<colour>]
//   {
//      (<x> <y> <z>)
//      [*SomeFlag One|Two|Three:sf]
//      [*SomethingElse:se:!sf]
//      $ObjectModifiers
//   }
//   @pos { <x> <y> <z> }
//   @o2w { <field> @pos } 
//   @colour {<aarrggbb>}
//   @ObjectModifiers
//   {
//      [*Something]
//      [@colour]
//      [@o2w]
//   }
// 
// Templates start with a keyword marked by '*', '@', or '$'
// '*' templates are basic template definitions, available for use at the given hierarchy level.
//     *templates at the root level go into the lookup table of shared templates.
// '@' templates are shared definitions for child templates. They are only available when referenced within another template
//     @templates at the root level go into the lookup table of shared templates.
//     @templates at child levels are placeholder references to a shared template.
// '$' templates are a reference to the children of a template.
//     $templates get expanded by adding each child in the referenced template to the parent of the $template.
// Literal text is text that is required.
// Text within <> is a field
//     <> fields cannot nest and must contain identifiers
// Text within [] is optional.
//     [] can also nest.
// Text within () is a repeatable section.
//     () implies one or more
//     [()] implies zero or more
// | means select one of the tokens on either side of the bar.
//     If the adjacent token is a [], or () select between the matched tokens.
//     This form: [one] | [two] | [three] means one of the options is required.
//     This form: [[one] | [two] | [three]] means the selection is optional.
// Templates should be multi-line, users can replace the \n characters with ' ' if needed.
// Templates can contain comments, but comments must not contain: {}[]()<>|*@$

#include <string>

namespace pr::ldr
{
	// Return the auto completion templates
	std::string AutoCompleteTemplates()
	{
		std::string str;
		str.reserve(4096);
		str.append(""

			// Global
			"*Clear {[(<ctx_id>)]}\n"
			"*AllowMissingIncludes\n"
			"*Camera\n"
			"{\n"
			"	[@o2w]\n"
			"	[*LookAt {<x> <y> <z>}]\n"
			"	[*Align {<x> <y> <z>}]\n"
			"	[*Aspect {<aspect>}]\n"
			"	[*FovX {<fovx>}]\n"
			"	[*FovY {<fovy>}]\n"
			"	[*Fov {<fovx> <fovy>}]\n"
			"	[*Near {<near>}]\n"
			"	[*Far {<far>}]\n"
			"	[*Orthographic]\n"
			"} \n"

			// Common
			"@o2w\n"
			"{\n"
			"	[*m4x4 {<xx> <xy> <xz> <xw>  <yx> <yy> <yz> <yw>  <zx> <zy> <zz> <zw>  <wx> <wy> <wz> <ww>}]\n"
			"	[*m3x3 {<xx> <xy> <xz>  <yx> <yy> <yz>  <zx> <zy> <zz>}]\n"
			"	[*pos {<x> <y> <z>}]\n"
			"	[*euler {<pitch> <yaw> <roll>}]\n"
			"	[*Align {<axis_id> <dx> <dy> <dz>}]\n"
			"	[*Scale {<sx> [<sy> <sz>]}]\n"
			"	[*Quat {<x> <y> <z> <s>}]\n"
			"	[*QuatPos {<qx> <qy> <qz> <qs>  <px> <py> <pz>}]\n"
			"	[*Rand4x4 {<x> <y> <z> <radius>}]\n"
			"	[*RandPos {<x> <y> <z> <radius>}]\n"
			"	[*RandOri]\n"
			"	[*Normalise]\n"
			"	[*Orthonormalise]\n"
			"	[*Transpose]\n"
			"	[*Inverse]\n"
			"}\n"
			"*Font\n"
			"{\n"
			"	[*Name {<family_name>}]\n"
			"	[*Size {<points>}]\n"
			"	[*Colour {<aarrggbb>}]\n"
			"	[*Weight {<weight_100_to_900>}]\n"
			"	[*Style {Normal|Italic|Oblique}]\n"
			"	[*Stretch {<stretch_1_to_9>}]\n"
			"	[*Underline]\n"
			"	[*Strikeout]\n"
			"}\n"
			"@Texture\n"
			"{\n"
			"	<texture_filepath>\n"
			"	[*Addr {Wrap|Mirror|Clamp|Border|MirrorOnce  Wrap|Mirror|Clamp|Border|MirrorOnce}]\n"
			"	[*Filter {Point|Linear|Anisotropic}]\n"
			"	[*Alpha]\n"
			"	[@o2w]\n"
			"}\n"
			"@Video\n"
			"{\n"
			"	<video_filepath>\n"
			"}\n"
			"@ObjectModifiers\n"
			"{\n"
			"	[@o2w]\n"
			"	[*Colour {<colour>}]\n"
			"	[*ColourMask {<mask>}]\n"
			"	[*Reflectivity {<amount>}]\n"
			"	[*RandColour]\n"
			"	[*Hidden]\n"
			"	[*Wireframe]\n"
			"	[*ScreenSpace]\n"
			"	[*NoZWrite]\n"
			"	[*NoZTest]\n"
			"	[*Animation\n"
			"	{\n"
			"		*Style NoAnimation|PlayOnce|PlayReverse|PingPong|PlayContinuous\n"
			"		*Period {<seconds>}\n"
			"		*Velocity {<vx> <vy> <vz>}\n"
			"		*AngVelocity {<ax> <ay> <az>}\n"
			"	}]\n"
			"	[@Font]\n"
			"}\n"
			"@Textured\n"
			"{\n"
			"	[@Texture]\n"
			"	[@Video]\n"
			"}\n"
			"@Coloured\n"
			"@Width {<thickness>}\n"
			"@Dashed {<on_length> <off_length>}\n"
			"@Param {<t0> <t1>}\n"
			"@Smooth\n"
			"@Solid\n"
			"@AxisId {<axis_id>}\n"

			// Special objects
			"*Instance [<name>] [<colour>]\n"
			"{\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Group [<name>] [<colour>]\n"
			"{\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Text [<name>] [<colour>]\n"
			"{\n"
			"	[*ScreenSpace|*Billboard]\n"
			"	([@Font])\n"
			"	(<text>)\n"
			"	([*CString {<c_style_string>}])\n"
			"	([*NewLine])\n"
			"	[*BackColour {<colour>}]\n"
			"	[*Anchor {<nss_x> <nss_y>}]\n"
			"	[*Padding {<left> <top> <right> <bottom>}]\n"
			"	[@AxisId]\n"
			"	[*Dim {<width> <height>}]\n"
			"	[*Format {Left|CentreH|Right Top|CentreV|Bottom NoWrap|Wrap|WholeWord|Character|EmergencyBreak}]\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*DirLight [<name>] [<colour>]\n"
			"{\n"
			"	<dx> <dy> <dz>\n"
			"	[*Specular {<colour> <power>}]\n"
			"	[*CastShadow {<range>}]\n"
			"	[@o2w]\n"
			"}\n"
			"*PointLight [<name>] [<colour>]\n"
			"{\n"
			"	<x> <y> <z>\n"
			"	[*Specular {<colour> <power>}]\n"
			"	[*Range {<range> <falloff>}]\n"
			"	[*CastShadow {<range>}]\n"
			"	[@o2w]\n"
			"}\n"
			"*SpotLight [<name>] [<colour>]\n"
			"{\n"
			"	<x> <y> <z>\n"
			"	<dx> <dy> <dz>\n"
			"	<inner_angle> <outer_angle>\n"
			"	[*Specular {<colour> <power>}]\n"
			"	[*Range {<range> <falloff>}]\n"
			"	[*CastShadow {<range>}]\n"
			"	[@o2w]\n"
			"}\n"

			// Point Sprites
			"*Point [<name>] [<colour>]\n"
			"{\n"
			"	[@Coloured]\n"
			"	(<x> <y> <z> [<colour>])\n"
			"	[*Size {<width> [<height>]}]\n"
			"	[*Style {Square|Circle|Triangle|Star|Annulus}]\n"
			"	[*Depth]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"

			// Line geometry
			"*Line [<name>] [<colour>]\n"
			"{\n"
			"	[@Coloured]\n"
			"	(<x0> <y0> <z0>  <x1> <y1> <z1> [<line_colour>] [@Param])\n"
			"	[@Width]\n"
			"	[@Dashed]\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*LineD [<name>] [<colour>]\n"
			"{\n"
			"	[@Coloured]\n"
			"	(<x0> <y0> <z0>  <dx> <dy> <dz> [<line_colour>] [@Param])\n"
			"	[@Width]\n"
			"	[@Dashed]\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*LineStrip [<name>] [<colour>]\n"
			"{\n"
			"	[@Coloured]\n"
			"	(<x> <y> <z> [<vertex_colour>])\n"
			"	[@Width]\n"
			"	[@Dashed]\n"
			"	[@Smooth]\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*LineBox [<name>] [<colour>]\n"
			"{\n"
			"	<width> [<height> [<depth>]]\n"
			"	[@Width]\n"
			"	[@Dashed]\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Grid [<name>] [<colour>]\n"
			"{\n"
			"	<width> <height>\n"
			"	[<width_divisions> <height_divisions>]\n"
			"	[@Width]\n"
			"	[@Dashed]\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Spline [<name>] [<colour>]\n"
			"{\n"
			"	[@Coloured]\n"
			"	(<x0> <y0> <z0>  <dx0> <dy0> <dz0>   <dx1> <dy1> <dz1>  <x1> <y1> <z1> [<colour>])\n"
			"	[@Width]\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Arrow [<name>] [<colour>]\n"
			"{\n"
			"	Line|Fwd|Back|FwdBack\n"
			"	[@Coloured]\n"
			"	(<x> <y> <z> [<vertex_colour>])\n"
			"	[@Width]\n"
			"	[@Smooth]\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Matrix3x3 [<name>] [<colour>]\n"
			"{\n"
			"	<xx> <xy> <xz>\n"
			"	<yx> <yy> <yz>\n"
			"	<zx> <zy> <zz>\n"
			"	[@Width]\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*CoordFrame [<name>] [<colour>]\n"
			"{\n"
			"	[*LeftHanded]\n"
			"	[*Scale {<scale>}]\n"
			"	[@Width]\n"
			"	$ObjectModifiers\n"
			"}\n"

			// 2D shapes
			"*Circle [<name>] [<colour>]\n"
			"{\n"
			"	<radius0> [<radius1>]\n"
			"	[*Facets {<facet_count>}]\n"
			"	[@AxisId]\n"
			"	[@Solid]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Pie [<name>] [<colour>]\n"
			"{\n"
			"	<angle0> <angle1>\n"
			"	<inner_radius> <outer_radius>\n"
			"	[*Facets {<facet_count>}]\n"
			"	[*Scale {<sx> <sy>}]\n"
			"	[@AxisId]\n"
			"	[@Solid]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Rect [<name>] [<colour>]\n"
			"{\n"
			"	<width> [<height>]\n"
			"	[*CornerRadius {<radius>}]\n"
			"	[*Facets {<facet_count>}]\n"
			"	[@AxisId]\n"
			"	[@Solid]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Polygon [<name>] [<colour>]\n"
			"{\n"
			"	[@Coloured]\n"
			"	(<x> <y> [<colour>])\n"
			"	[@AxisId]\n"
			"	[@Solid]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"

			// Quad shapes
			"*Triangle [<name>] [<colour>]\n"
			"{\n"
			"	[@Coloured]\n"
			"	<pt0_x> <pt0_y> <pt0_z> [<colour>]\n"
			"	<pt1_x> <pt1_y> <pt1_z> [<colour>]\n"
			"	<pt2_x> <pt2_y> <pt2_z> [<colour>]\n"
			"	[@AxisId]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Quad [<name>] [<colour>]\n"
			"{\n"
			"	[@Coloured]\n"
			"	<pt0_x> <pt0_y> <pt0_z> [<colour>]\n"
			"	<pt1_x> <pt1_y> <pt1_z> [<colour>]\n"
			"	<pt2_x> <pt2_y> <pt2_z> [<colour>]\n"
			"	<pt3_x> <pt3_y> <pt3_z> [<colour>]\n"
			"	[@AxisId]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Plane [<name>] [<colour>]\n"
			"{\n"
			"	<centre_x> <centre_y> <centre_z>\n"
			"	<normal_x> <normal_y> <normal_z>\n"
			"	<width> <height>\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Ribbon [<name>] [<colour>]\n"
			"{\n"
			"	[@Coloured]\n"
			"	(<x> <y> <z> [<colour>])\n"
			"	[@AxisId]\n"
			"	[@Width]\n"
			"	[@Smooth]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"

			// 3D shapes
			"*Box [<name>] [<colour>]\n"
			"{\n"
			"	<width> [<height> [depth]]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Bar [<name>] [<colour>]\n"
			"{\n"
			"	<x0> <y0> <z0>  <x1> <y1> <z1>\n"
			"	<width> [<height>]\n"
			"	[*Up {<dx> <dy> <dz>}]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*BoxList [<name>] [<colour>]\n"
			"{\n"
			"	<width> <height> <depth>.\n"
			"	(<x> <y> <z>)\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*FrustumWH [<name>] [<colour>]\n"
			"{\n"
			"	<width> <height>\n"
			"	<near> <far>\n"
			"	[*ViewPlaneZ {<distance_of_width_height>}]\n"
			"	[@AxisId]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*FrustumFA [<name>] [<colour>]\n"
			"{\n"
			"	<fovY> <aspect>\n"
			"	<near> <far>\n"
			"	[@AxisId]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Sphere [<name>] [<colour>]\n"
			"{\n"
			"	<radius0> [<radius1> [<radius2>]]\n"
			"	[*Facets {<facet_count>}]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*CylinderHR [<name>] [<colour>]\n"
			"{\n"
			"	<height> <radius> [<radius_tip>]\n"
			"	[*Facets {<layers>, <wedges>}]\n"
			"	[*Scale {<sx> <sy>}]\n"
			"	[@AxisId]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*ConeHA [<name>] [<colour>]\n"
			"{\n"
			"	<tip_to_top> <tip_to_base> <solid_angle>\n"
			"	[*Facets {<layers>, <wedges>}]\n"
			"	[*Scale {<sx> <sy>}]\n"
			"	[@AxisId]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Tube [<name>] [<colour>]\n"
			"{\n"
			"	*Style\n"
			"	{\n"
			"		[Round <radius0> [<radius1>] [*Facets {<facet_count>}]] |\n"
			"		[Square <radius0> [<radius1>]] |\n"
			"		[CrossSection (<x> <y>) [@Smooth]]\n"
			"	}\n"
			"	[@Coloured]\n"
			"	(<x> <y> <z> [<colour>])\n"
			"	[@Smooth]\n"
			"	[*Closed]\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Mesh [<name>] [<colour>]\n"
			"{\n"
			"	*Verts {(<x> <y> <z>)}\n"
			"	[*Normals {(<nx> <ny> <nz>)}]\n"
			"	[*Colours {(<colour>)}]\n"
			"	[*TexCoords {(<tx> <ty>)}]\n"
			"	[*Faces {(<i0> <i1> <i2>)}]\n"
			"	[*Lines {(<i0> <i1>)}]\n"
			"	[*Tetra {(<i0> <i1> <i2> <i3>)}]\n"
			"	[*GenerateNormals {<smoothing_angle>}]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*ConvexHull [<name>] [<colour>]\n"
			"{\n"
			"	*Verts {(<x> <y> <z>)}\n"
			"	[*GenerateNormals {<smoothing_angle>}]\n"
			"	$Textured\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Chart [<name>] [<colour>]\n"
			"{\n"
			"	[#include <csv_filepath>] |\n"
			"	[\n"
			"		[(<column_header>)]\n"
			"		(<x_data> (<y_data>))\n"
			"	]\n"
			"	[*XColumn {<x_axis_column_number>}]\n"
			"	[*XAxis {<x_axis_y_intercept>}]\n"
			"	[*YAxis {<y_axis_x_intercept>}]\n"
			"	[*Colours {(<column_colour>)}]\n"
			"	[*Width {<line_plot_width>}]\n"
			"	[@AxisId]\n"
			"	$ObjectModifiers\n"
			"}\n"
			"*Model [<name>] [<colour>]\n"
			"{\n"
			"	<model_filepath>\n"
			"	[*Part {<submodel_index>}]\n"
			"	[*GenerateNormals {<smoothing_angle>}]\n"
			"	[*BakeTransform {$o2w}]\n"
			"	$ObjectModifiers\n"
			"}\n"
			);
		return str;
	}
}
