//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyLogViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RyLogViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap background2 {
            get {
                object obj = ResourceManager.GetObject("background2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap book {
            get {
                object obj = ResourceManager.GetObject("book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bookmark {
            get {
                object obj = ResourceManager.GetObject("bookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bottom {
            get {
                object obj = ResourceManager.GetObject("bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿&lt;!DOCTYPE HTML&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Command Line Syntax&lt;/title&gt;
        ///		﻿&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///		
        ///
        ///		﻿&lt;!--&lt;meta http-equiv=&quot;refresh&quot; content=&quot;3&quot;/&gt;--&gt;
        ///
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			* {
        ///				font-family: sans-serif;
        ///				font-size: 100%;
        ///				font-weight: normal;
        ///			}
        ///		
        ///			table {
        ///				border: 1px solid #006000;
        ///				border-collapse: collapse;
        ///				width: 100% [rest of string was truncated]&quot;;.
        /// </summary>
        public static string command_line_ref {
            get {
                return ResourceManager.GetString("command_line_ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿&lt;!DOCTYPE HTML&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Aggregate Files Licensed Feature&lt;/title&gt;
        ///		﻿&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///		
        ///
        ///		﻿&lt;!--&lt;meta http-equiv=&quot;refresh&quot; content=&quot;3&quot;/&gt;--&gt;
        ///
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			* {
        ///				font-family: sans-serif;
        ///				font-size: 11pt;
        ///			}
        ///		
        ///			body {
        ///				background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUoAAAFWCAYAAAAPPdTlAAAABGd [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cripple_aggregate_files {
            get {
                return ResourceManager.GetString("cripple_aggregate_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿&lt;!DOCTYPE HTML&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Filtering Patterns Licensed Feature&lt;/title&gt;
        ///		﻿&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///		
        ///
        ///		﻿&lt;!--&lt;meta http-equiv=&quot;refresh&quot; content=&quot;3&quot;/&gt;--&gt;
        ///
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			* {
        ///				font-family: sans-serif;
        ///				font-size: 11pt;
        ///			}
        ///		
        ///			body {
        ///				background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUoAAAFWCAYAAAAPPdTlAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cripple_filtering {
            get {
                return ResourceManager.GetString("cripple_filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿&lt;!DOCTYPE HTML&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Highlighting Patterns Licensed Feature&lt;/title&gt;
        ///		﻿&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///		
        ///
        ///		﻿&lt;!--&lt;meta http-equiv=&quot;refresh&quot; content=&quot;3&quot;/&gt;--&gt;
        ///
        ///		﻿
        ///		
        ///		
        ///		
        ///		
        ///
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			* {
        ///				font-family: sans-serif;
        ///				font-size: 11pt;
        ///			}
        ///		
        ///			body {
        ///				background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cripple_highlighting {
            get {
                return ResourceManager.GetString("cripple_highlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap edit_add {
            get {
                object obj = ResourceManager.GetObject("edit_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap edit_save {
            get {
                object obj = ResourceManager.GetObject("edit_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap edit_save_needed {
            get {
                object obj = ResourceManager.GetObject("edit_save_needed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exchange {
            get {
                object obj = ResourceManager.GetObject("exchange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap execute {
            get {
                object obj = ResourceManager.GetObject("execute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Eyeball {
            get {
                object obj = ResourceManager.GetObject("Eyeball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap find_search {
            get {
                object obj = ResourceManager.GetObject("find_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;First Run Tutorial&lt;/title&gt;
        ///		﻿&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///		
        ///
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			* {
        ///				font-family: sans-serif;
        ///				font-size: 10pt;
        ///			}
        ///
        ///			body {
        ///				background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUoAAAFWCAYAAAAPPdTlAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwgAADsIBFShKgAAAABp0RVh0U29mdHdhcmUAUGFpbn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string firstrun {
            get {
                return ResourceManager.GetString("firstrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_with_file {
            get {
                object obj = ResourceManager.GetObject("folder_with_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿&lt;!DOCTYPE HTML&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Free Version&lt;/title&gt;
        ///		﻿&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///		
        ///
        ///		﻿&lt;!--&lt;meta http-equiv=&quot;refresh&quot; content=&quot;3&quot;/&gt;--&gt;
        ///
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			* {
        ///				font-family: sans-serif;
        ///				font-size: 12pt;
        ///			}
        ///
        ///			body {
        ///				background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAA4CAYAAACohjseAAAABGdBTUEAALGPC/xhBQAAAAlwS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string free_version {
            get {
                return ResourceManager.GetString("free_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap green_down {
            get {
                object obj = ResourceManager.GetObject("green_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap green_up {
            get {
                object obj = ResourceManager.GetObject("green_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap highlight {
            get {
                object obj = ResourceManager.GetObject("highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap important {
            get {
                object obj = ResourceManager.GetObject("important", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap options {
            get {
                object obj = ResourceManager.GetObject("options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pattern_active {
            get {
                object obj = ResourceManager.GetObject("pattern_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pattern_inactive {
            get {
                object obj = ResourceManager.GetObject("pattern_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RSAKeyValue&gt;
        ///  &lt;Modulus&gt;miDmCy/hXV9YZFFc3sOKcYDDV2e49MeRvCb2ghpJBQFnSRVCeAmRtc8Vfm4meMuye/tnDGcYWf1t5J1llYstA1+26/AuTPDCrTXEU/FObmIWUwfpzlWfh4ZBzx0hBDJFUpWbncCKXvOxIubc1NhMDK1yuYLG2FEucx6V/yLcEiU=&lt;/Modulus&gt;
        ///  &lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///&lt;/RSAKeyValue&gt;.
        /// </summary>
        public static string public_key {
            get {
                return ResourceManager.GetString("public_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap quick_filter {
            get {
                object obj = ResourceManager.GetObject("quick_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Swizzle - Quick Reference&lt;/title&gt;
        ///		﻿&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///		
        ///
        ///		﻿&lt;!--&lt;meta http-equiv=&quot;refresh&quot; content=&quot;3&quot;/&gt;--&gt;
        ///
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			* {
        ///				font-family: sans-serif;
        ///				font-size: 100%;
        ///				font-weight: normal;
        ///			}
        ///		
        ///			table {
        ///				border: 1px solid #006000;
        ///				border-collapse: collapse;
        ///				width: 100%;
        ///				marg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string swizzle_quick_ref {
            get {
                return ResourceManager.GetString("swizzle_quick_ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;First Run Tutorial&lt;/title&gt;
        ///		﻿&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///		
        ///
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			* {
        ///				font-family: sans-serif;
        ///				font-size: 10pt;
        ///			}
        ///
        ///			body {
        ///				background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAA4CAYAAACohjseAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAA3WgAAN1oBS8TgIgAAABh0RVh0U29mdHdhcmUAcGFpbn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string totd {
            get {
                return ResourceManager.GetString("totd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﻿&lt;!DOCTYPE HTML&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Transforms - Quick Reference&lt;/title&gt;
        ///		﻿&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///		
        ///
        ///		﻿&lt;!--&lt;meta http-equiv=&quot;refresh&quot; content=&quot;3&quot;/&gt;--&gt;
        ///
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			* {
        ///				font-family: sans-serif;
        ///				font-size: 100%;
        ///				font-weight: normal;
        ///			}
        ///		
        ///			table {
        ///				border: 1px solid #006000;
        ///				border-collapse: collapse;
        ///				wi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string transform_quick_ref {
            get {
                return ResourceManager.GetString("transform_quick_ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Version History&lt;/title&gt;
        ///		﻿&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///		
        ///
        ///		﻿&lt;!--&lt;meta http-equiv=&quot;refresh&quot; content=&quot;3&quot;/&gt;--&gt;
        ///
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			* {
        ///				font-family: sans-serif;
        ///				font-size: 100%;
        ///				font-weight: normal;
        ///			}
        ///		
        ///			table {
        ///				border: 1px solid #006000;
        ///				border-collapse: collapse;
        ///				width: 100%;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string version_history {
            get {
                return ResourceManager.GetString("version_history", resourceCulture);
            }
        }
    }
}
