//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyLogViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RyLogViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assume log file changes are additive only. If enabled, only additions to the
        ///file will be scanned allowing increased performance. The view may get out of sync if the
        ///log file is modified in a way that isn&apos;t additive (e.g. lines swapped, deleted, etc).
        /// </summary>
        internal static string AdditiveMode {
            get {
                return ResourceManager.GetString("AdditiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RyLogViewer.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Match.
        /// </summary>
        internal static string BinaryMatch {
            get {
                return ResourceManager.GetString("BinaryMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book {
            get {
                object obj = ResourceManager.GetObject("book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bookmark {
            get {
                object obj = ResourceManager.GetObject("bookmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bottom {
            get {
                object obj = ResourceManager.GetObject("bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building line index.
        /// </summary>
        internal static string BuildingLineIndex {
            get {
                return ResourceManager.GetString("BuildingLineIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The was an error while parsing the log file.
        ///Error Details:
        ///{0}.
        /// </summary>
        internal static string BuildLineIndexErrorMsg {
            get {
                return ResourceManager.GetString("BuildLineIndexErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Background Colour.
        /// </summary>
        internal static string ChangeBackColour {
            get {
                return ResourceManager.GetString("ChangeBackColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Foregroud Colour.
        /// </summary>
        internal static string ChangeForeColour {
            get {
                return ResourceManager.GetString("ChangeForeColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an output file name.
        /// </summary>
        internal static string ChooseOutputFileName {
            get {
                return ResourceManager.GetString("ChooseOutputFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log Failed.
        /// </summary>
        internal static string ClearLogFailed {
            get {
                return ResourceManager.GetString("ClearLogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify action.
        /// </summary>
        internal static string ClickToModifyAction {
            get {
                return ResourceManager.GetString("ClickToModifyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to modify highlight.
        /// </summary>
        internal static string ClickToModifyHighlight {
            get {
                return ResourceManager.GetString("ClickToModifyHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Clear Log.
        /// </summary>
        internal static string ConfirmClearLog {
            get {
                return ResourceManager.GetString("ConfirmClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Overwrite.
        /// </summary>
        internal static string ConfirmOverwrite {
            get {
                return ResourceManager.GetString("ConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete pattern set file {0}.
        ///Error: {1}.
        /// </summary>
        internal static string CouldNotDeletePatternSetFileX {
            get {
                return ResourceManager.GetString("CouldNotDeletePatternSetFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pattern Set Failed.
        /// </summary>
        internal static string CreatePatternSetFailed {
            get {
                return ResourceManager.GetString("CreatePatternSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a pattern set from the current patterns.
        ///Error: {0}.
        /// </summary>
        internal static string CreatePatternSetFailedMsg {
            get {
                return ResourceManager.GetString("CreatePatternSetFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Files (*.csv)|*.csv|All files (*.*)|*.*.
        /// </summary>
        internal static string CSVFileFilter {
            get {
                return ResourceManager.GetString("CSVFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed.
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete pattern set file &apos;{0}&apos;?.
        /// </summary>
        internal static string DeletePatternSetFileX {
            get {
                return ResourceManager.GetString("DeletePatternSetFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Files (*.dmp)|*.dmp|All files (*.*)|*.*.
        /// </summary>
        internal static string DumpFileFilter {
            get {
                return ResourceManager.GetString("DumpFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_add {
            get {
                object obj = ResourceManager.GetObject("edit_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_save {
            get {
                object obj = ResourceManager.GetObject("edit_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_save_needed {
            get {
                object obj = ResourceManager.GetObject("edit_save_needed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding: {0}.
        /// </summary>
        internal static string EncodingX {
            get {
                return ResourceManager.GetString("EncodingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exchange {
            get {
                object obj = ResourceManager.GetObject("exchange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        internal static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executables (*.exe;*.bat;*.cmd;*.com)|*.exe;*.bat;*.cmd;*.com|All files (*.*)|*.*.
        /// </summary>
        internal static string ExecutablesFilter {
            get {
                return ResourceManager.GetString("ExecutablesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap execute {
            get {
                object obj = ResourceManager.GetObject("execute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Complete.
        /// </summary>
        internal static string ExportComplete {
            get {
                return ResourceManager.GetString("ExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed successfully.
        /// </summary>
        internal static string ExportCompletedSuccessfully {
            get {
                return ResourceManager.GetString("ExportCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Failed.
        /// </summary>
        internal static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eyeball {
            get {
                object obj = ResourceManager.GetObject("Eyeball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Launch Process.
        /// </summary>
        internal static string FailedToLaunchProcess {
            get {
                return ResourceManager.GetString("FailedToLaunchProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file.
        /// </summary>
        internal static string FailedToLoadFile {
            get {
                return ResourceManager.GetString("FailedToLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find_search {
            get {
                object obj = ResourceManager.GetObject("find_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_with_file {
            get {
                object obj = ResourceManager.GetObject("folder_with_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_down {
            get {
                object obj = ResourceManager.GetObject("green_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_up {
            get {
                object obj = ResourceManager.GetObject("green_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highlight {
            get {
                object obj = ResourceManager.GetObject("highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighting.
        /// </summary>
        internal static string Highlighting {
            get {
                return ResourceManager.GetString("Highlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Match....
        /// </summary>
        internal static string IfMatch {
            get {
                return ResourceManager.GetString("IfMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap important {
            get {
                object obj = ResourceManager.GetObject("important", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Path.
        /// </summary>
        internal static string InvalidFilePath {
            get {
                return ResourceManager.GetString("InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Ending: {0}.
        /// </summary>
        internal static string LineEndingX {
            get {
                return ResourceManager.GetString("LineEndingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: {0}/{1}.
        /// </summary>
        internal static string LineXofY {
            get {
                return ResourceManager.GetString("LineXofY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Pattern Set Failed.
        /// </summary>
        internal static string LoadPatternSetFailed {
            get {
                return ResourceManager.GetString("LoadPatternSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt;*.log;*.csv)|*.txt;*.log;*.csv|All files (*.*)|*.*.
        /// </summary>
        internal static string LogFileFilter {
            get {
                return ResourceManager.GetString("LogFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File.
        /// </summary>
        internal static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a log file.
        /// </summary>
        internal static string OpenLogFile {
            get {
                return ResourceManager.GetString("OpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap options {
            get {
                object obj = ResourceManager.GetObject("options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file missing.
        /// </summary>
        internal static string OutputFileMissing {
            get {
                return ResourceManager.GetString("OutputFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file missing. Please select a file to export to.
        /// </summary>
        internal static string OutputFileMissingMsg {
            get {
                return ResourceManager.GetString("OutputFileMissingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        internal static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pattern_active {
            get {
                object obj = ResourceManager.GetObject("pattern_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pattern_inactive {
            get {
                object obj = ResourceManager.GetObject("pattern_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: {0} / {1} bytes.
        /// </summary>
        internal static string PositionXofYBytes {
            get {
                return ResourceManager.GetString("PositionXofYBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RSAKeyValue&gt;
        ///  &lt;Modulus&gt;miDmCy/hXV9YZFFc3sOKcYDDV2e49MeRvCb2ghpJBQFnSRVCeAmRtc8Vfm4meMuye/tnDGcYWf1t5J1llYstA1+26/AuTPDCrTXEU/FObmIWUwfpzlWfh4ZBzx0hBDJFUpWbncCKXvOxIubc1NhMDK1yuYLG2FEucx6V/yLcEiU=&lt;/Modulus&gt;
        ///  &lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string public_key {
            get {
                return ResourceManager.GetString("public_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quick_filter {
            get {
                object obj = ResourceManager.GetObject("quick_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick filter; keep highlighted rows only.
        /// </summary>
        internal static string QuickFilter {
            get {
                return ResourceManager.GetString("QuickFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading File Failed.
        /// </summary>
        internal static string ReadingFileFailed {
            get {
                return ResourceManager.GetString("ReadingFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading the last {0} lines from {1}.
        /// </summary>
        internal static string ReadingXLineFromY {
            get {
                return ResourceManager.GetString("ReadingXLineFromY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload the current log file.
        /// </summary>
        internal static string ReloadLogFile {
            get {
                return ResourceManager.GetString("ReloadLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to the last log file row.
        /// </summary>
        internal static string ScrollToEnd {
            get {
                return ResourceManager.GetString("ScrollToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to the first log file row.
        /// </summary>
        internal static string ScrollToStart {
            get {
                return ResourceManager.GetString("ScrollToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string SettingsFileFilter {
            get {
                return ResourceManager.GetString("SettingsFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to enable/disable actions.
        ///Right click to show the actions dialog.
        /// </summary>
        internal static string ShowActionsDialog {
            get {
                return ResourceManager.GetString("ShowActionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the bookmarks dialog.
        /// </summary>
        internal static string ShowBookmarksDialog {
            get {
                return ResourceManager.GetString("ShowBookmarksDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to enable/disable filters.
        ///Right click to show the filters dialog.
        /// </summary>
        internal static string ShowFiltersDialog {
            get {
                return ResourceManager.GetString("ShowFiltersDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the find dialog.
        /// </summary>
        internal static string ShowFindDialog {
            get {
                return ResourceManager.GetString("ShowFindDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to enable/disable highlighting.
        ///Right click to show the highlighting dialog.
        /// </summary>
        internal static string ShowHighlightsDialog {
            get {
                return ResourceManager.GetString("ShowHighlightsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to enable/disable transforms.
        ///Right click to show the transforms dialog.
        /// </summary>
        internal static string ShowTransformsDialog {
            get {
                return ResourceManager.GetString("ShowTransformsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command line option.
        /// </summary>
        internal static string UnknownCmdLineOption {
            get {
                return ResourceManager.GetString("UnknownCmdLineOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch the file and update automatically when it changes.
        /// </summary>
        internal static string WatchForUpdates {
            get {
                return ResourceManager.GetString("WatchForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically scroll to the bottom of the log as new data is loaded.
        /// </summary>
        internal static string WatchTail {
            get {
                return ResourceManager.GetString("WatchTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml)|*.xml|CSV Files (*.csv)|*.csv.
        /// </summary>
        internal static string XmlOrCsvFileFilter {
            get {
                return ResourceManager.GetString("XmlOrCsvFileFilter", resourceCulture);
            }
        }
    }
}
