//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LineDrawer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LINEDRAWER_DIALOG           102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_HTML_ADDOBJECT              104
#define IDR_MAINFRAME                   128
#define IDR_MAINMENU                    129
#define IDD_VIEW_DIALOG                 130
#define IDD_AUTOCLEAR_DIALOG            131
#define IDD_NETWORKSETTINGS_DIALOG      132
#define IDD_LIGHTING_DIALOG             134
#define ID_RENDERING_LIGHTING           135
#define ID_RENDERING_COORDINATES        136
#define ID_WINDOW_BACKGROUNDCOLOUR      137
#define ID_DATA_DISABLEALL              138
#define ID_DATA_ENABLEALL               139
#define ID_DATA_CLEAR                   140
#define ID_FILE_NEWOBJECT               142
#define IDD_DATA_LIST                   143
#define ID_DATA_DATALIST                144
#define IDD_ADD_OBJECT                  145
#define ID_NAVIGATION_ZOOMTOVISIBLE     146
#define ID_FILE_ADDITIVEOPEN            147
#define ID_NAVIGATION_LOOKATORIGIN      148
#define ID_DATA_SHOWSELECTION           149
#define ID_NAVIGATION_INERTIALCAMERA    150
#define ID_NAVIGATION_SHOWFOCUSPOINT    151
#define ID_DATA_AUTOREFRESH             152
#define IDD_AUTOREFRESH                 153
#define IDD_PROGRESS                    154
#define ID_FILE_SETERROROUTPUT          155
#define ID_WINDOW_VIEW                  158
#define ID_VIEW_TOPDOWN                 159
#define ID_VIEW_BOTTOMUP                160
#define ID_VIEW_LEFTSIDE                161
#define ID_VIEW_RIGHTSIDE               162
#define ID_VIEW_FRONT                   163
#define ID_VIEW_BACK                    164
#define ID_NAVIGATION_ZOOMTOSELECTED    165
#define ID_DATA_STARTCYCLICOBJECTS      166
#define ID_NAVIGATION_SHOWORIGIN        167
#define ID_NAVIGATION_SHOWAXIS          168
#define ID_DATA_STARTANIMATIONS         169
#define ID_NAVIGATION_LOCK              170
#define ID_NAVIGATION_LOCK171           171
#define ID_LOCK_TRANSLATION             172
#define ID_LOCK_ROTATION                173
#define ID_Menu                         174
#define ID_JUMPTO_ORIGIN                175
#define ID_JUMPTO_VISIBLE               176
#define ID_JUMPTO_SELECTED              177
#define ID_LOCK_ZOOM                    178
#define ID_FILE_SAVEAS                  179
#define ID_FILE_RUNPLUGIN               180
#define ID_WINDOW_STEREOVIEW            181
#define ID_RENDERING_STEREOVIEW         182
#define ID_WINDOW_LINEDRAWERHELP        183
#define ID_WINDOW_LINEDRAWERHELPINDEX   184
#define ID_NAVIGATION_LOCKTOSELECTION   187
#define ID_ROTATION_X                   188
#define ID_ROTATION_Y                   189
#define ID_ROTATION_Z                   190
#define ID_TRANSLATION_X                191
#define ID_TRANSLATION_Y                192
#define ID_TRANSLATION_Z                193
#define IDR_ACCELERATOR1                194
#define IDR_ACCELERATOR2                196
#define ID_FILE_RECENTFILES             199
#define ID_RECENTFILES_RECENTFILESSTART 200
#define ID_RECENTFILES_RECENTFILESLAST  220
#define IDD_ANIMATION_CONTROL           221
#define ID_LOCK_CAMERARELATIVE          222
#define ID_FILE_OPTIONS                 223
#define IDD_DIALOG1                     224
#define IDD_OPTIONS                     224
#define ID_NAVIGATION_INERTIALCAMERATYPE 226
#define ID_INERTIALCAMERATYPE_FULL3D    227
#define ID_INERTIALCAMERATYPE_YLOCKED   228
#define IDD_LOCKS                       229
#define IDD_COLOUR_TYPEIN               230
#define IDD_COORDINATES                 232
#define IDC_EDIT_WIDTH                  1000
#define IDC_EDIT_CAMX                   1000
#define IDC_EDIT_CAM_POSITION           1000
#define IDC_STATIC_FAR                  1001
#define IDC_STATIC_DIFFUSE              1001
#define IDC_STATIC_NEAR                 1002
#define IDC_STATIC_AMBIENT              1002
#define IDC_STATIC_HEIGHT               1003
#define IDC_STATIC_GLOBALAMBIENT        1003
#define IDC_STATIC_WIDTH                1004
#define IDC_EDIT_HEIGHT                 1005
#define IDC_EDIT_AutoClear              1005
#define IDC_STATIC_HEIGHT4              1005
#define IDC_EDIT_NEAR                   1006
#define IDC_EDIT_IP1                    1006
#define IDC_STATIC_HEIGHT5              1006
#define IDC_EDIT_FAR                    1007
#define IDC_EDIT_IP2                    1007
#define IDC_EDIT_IP3                    1008
#define IDC_EDIT_CAMY                   1008
#define IDC_EDIT_IP4                    1009
#define IDC_EDIT_CAMZ                   1009
#define IDC_EDIT_PORT                   1010
#define IDC_EDIT_CAMFX                  1010
#define IDC_EDIT_CAM_FORWARD            1010
#define IDC_EDIT_SAMPLE_PERIOD          1011
#define IDC_EDIT_CAMFY                  1011
#define IDC_EDIT_FOCUS_POSITION         1011
#define IDC_EDIT_RECV_BUFFER_SIZE       1012
#define IDC_EDIT_CAMFZ                  1012
#define IDC_COMBO_CULLMODE              1013
#define IDC_CHECK_Aspect_lock           1014
#define IDC_STATIC_HEIGHT2              1014
#define IDC_EDIT_CAMUX                  1015
#define IDC_CHECK_AMBIENT               1015
#define IDC_LOCK_CAMERA_RELATIVE        1015
#define IDC_EDIT_CAM_UP                 1015
#define IDC_EDIT_CAMUY                  1016
#define IDC_LIGHTING_AMBIENT_RED        1016
#define IDC_STATIC_HEIGHT3              1016
#define IDC_EDIT_CAMFZ2                 1017
#define IDC_EDIT_CAMUZ                  1017
#define IDC_LIGHTING_AMBIENT_GREEN      1017
#define IDC_EDIT_CAM_LEFT               1017
#define IDC_LIGHTING_AMBIENT_BLUE       1018
#define IDC_RADIO_POINT                 1020
#define IDC_LIGHTING_SPECULAR_RED       1021
#define IDC_LIGHTING_SPECULAR_GREEN     1022
#define IDC_LIGHTING_SPECULAR_BLUE      1023
#define IDC_RADIO_SPOT                  1025
#define IDC_RADIO_DIRECTIONAL           1026
#define IDC_CHECK_LIGHTSOURCE           1027
#define IDC_LIGHTING_EMISSIVE_RED       1027
#define IDC_LIGHTING_DIFFUSE_RED        1028
#define IDC_LIGHTING_DIFFUSE_GREEN      1029
#define IDC_LIGHTING_DIFFUSE_BLUE       1030
#define IDC_LIGHTING_POSITION_X         1032
#define IDC_LIGHTING_POSITION_Y         1033
#define IDC_LIGHTING_POSITION_Z         1034
#define IDC_LIGHTING_DIRECTION_X        1035
#define IDC_LIGHTING_DIRECTION_Y        1036
#define IDC_LIGHTING_DIRECTION_Z        1037
#define IDC_LIGHTING_INNER_SOLID_ANGLE  1038
#define IDC_LIGHTING_OUTER_SOLID_ANGLE  1039
#define IDC_STATIC_TYPE                 1040
#define IDC_LIGHTING_RANGE              1040
#define IDC_STATIC_SPECULAR             1041
#define IDC_STATIC_LIGHT_POSITION       1042
#define IDC_STATIC_LIGHT_DIRECTION      1043
#define IDC_STATIC_LIGHT_INNER_SOLID_ANGLE 1044
#define IDC_STATIC_LIGHT_OUTER_SOLID_ANGLE 1045
#define IDC_BUTTON_APPLY                1046
#define IDC_STATIC_LIGHTING_RED         1047
#define IDC_STATIC_LIGHTING_GREEN       1048
#define IDC_STATIC_LIGHTING_BLUE        1049
#define IDC_STATIC_LIGHTING_ALPHA       1050
#define IDC_STATIC_LIGHTING_CAMERA_RELATIVE 1051
#define IDC_STATIC_LIGHT_RANGE          1052
#define IDC_STATIC_LIGHT_FALLOFF        1053
#define IDC_LIGHTING_FALLOFF            1054
#define IDC_STATIC_LIGHT_DEGREES1       1055
#define IDC_STATIC_LIGHT_DEGREES2       1056
#define IDC_STATIC_LIGHT_ATTENUATION    1057
#define IDC_LIGHTING_ATTEN0             1058
#define IDC_LIGHTING_ATTEN1             1059
#define IDC_LIGHTING_ATTEN2             1060
#define IDC_CHECK_CAST_SHADOWS          1061
#define IDC_RADIO_POINT2                1061
#define IDC_RADIO_AMBIENT               1061
#define IDC_LIGHTING_EMISSIVE_GREEN     1062
#define IDC_LIGHTING_EMISSIVE_BLUE      1063
#define IDC_LIGHTING_EMISSIVE_ALPHA     1064
#define IDC_STATIC_EMISSIVE             1065
#define IDC_LIGHTING_SPECULAR_POWER     1066
#define IDC_STATIC_SPECULAR_POWER       1067
#define IDC_LIGHTING_GLOBALAMBIENT_RED  1068
#define IDC_EDIT_ADD_OBJECT             1069
#define IDC_LIGHTING_GLOBALAMBIENT_GREEN 1069
#define IDC_LIST_DATA                   1070
#define IDC_LIGHTING_GLOBALAMBIENT_BLUE 1070
#define IDC_BUTTON_DEL_SELECTION        1071
#define IDC_LIGHTING_GLOBALAMBIENT_ALPHA 1071
#define IDC_EDIT_SELECT_MASK            1072
#define IDC_BUTTON_HIDE                 1073
#define IDC_BUTTON_UNHIDE_ALL           1074
#define IDC_BUTTON_INV_SELECTION        1075
#define IDC_BUTTON_TOGGLE_WIRE          1076
#define IDC_BUTTON_HIDE_ALL             1077
#define IDC_BUTTON1                     1078
#define IDC_BUTTON_UNHIDE               1078
#define IDC_BUTTON_ERRORFILE_FIND       1078
#define IDC_ANIMATION_PAUSE             1078
#define IDC_OPTIONS_BUTTON_ERRORFILE_FIND 1078
#define IDC_BUTTON_COPY_CAM_XFORM       1078
#define IDC_BUTTON_TOGGLE_VISIBILITY    1079
#define IDC_BUTTON_WIREFRAME            1080
#define IDC_EDIT1                       1081
#define IDC_EDIT_REFRESH_FREQUENCY      1081
#define IDC_EDIT_ERRORLOG_FILENAME      1081
#define IDC_BUTTON_UNWIREFRAME          1081
#define IDC_EDIT_NEAR_CLIP_PLANE        1081
#define IDC_EDIT_TIME_MULTIPLIER        1081
#define IDC_EDIT_ANIMATION_TIME_MULTIPLIER 1081
#define IDC_OPTIONS_EDIT_ERRORLOG_FILENAME 1081
#define IDC_COLOUR_TYPEIN_AA            1081
#define IDC_EDIT_FOCUS_COORDS           1081
#define IDC_STATIC_REFRESH_FREQUENCY    1082
#define IDC_BUTTON_WIREFRAME_ALL        1082
#define IDC_COLOUR_TYPEIN_RR            1082
#define IDC_EDIT_MOUSE_COORDS           1082
#define IDC_PROGRESS_BAR                1083
#define IDC_BUTTON_UNWIREFRAME_ALL      1083
#define IDC_COLOUR_TYPEIN_GG            1083
#define IDC_STATIC_PROGRESS_DESCRIPTION 1084
#define IDC_BUTTON_HIDE_SUB             1084
#define IDC_COLOUR_TYPEIN_BB            1084
#define IDC_BUTTON_UNHIDE_SUB           1085
#define IDC_CHECK_ERROR_MSGBOX          1086
#define IDC_BUTTON_WIREFRAME_SUB        1086
#define IDC_CHECK_ERROR_LOGTOFILE       1087
#define IDC_BUTTON_UNWIREFRAME_SUB      1087
#define IDC_DATA_TREE                   1088
#define IDC_CHECK_IGNORE_MISSING_INCLUDES 1088
#define IDC_BUTTON_EXPAND_ALL           1089
#define IDC_BUTTON_COLLAPSE_ALL         1090
#define IDC_BUTTON_EDIT_SELECTION       1091
#define IDC_BUTTON_DEL_SELECTION2       1094
#define IDC_BUTTON_SET_COLOUR           1094
#define IDC_BUTTON_SET_COLOUR2          1095
#define IDC_SPLITTER_CTRL               1096
#define IDC_CHECK_AUTORECENTRE          1099
#define IDC_EDIT_FAR_CLIP_PLANE         1100
#define IDC_CHECK1                      1102
#define IDC_CHECK_CameraRelative        1102
#define IDC_CHECK_RESET_CAMERA_ON_LOAD  1102
#define IDC_LOCK_TRANSLATION_X          1102
#define IDC_SLIDER_TIME_MULTIPLIER      1103
#define IDC_LOCK_TRANSLATION_Y          1103
#define IDC_BUTTON_ANIMATION_PAUSE      1104
#define IDC_LOCK_TRANSLATION_Z          1104
#define IDC_BUTTON_ANIMATION_STEP_FORWARD 1105
#define IDC_LOCK_ROTATION_X             1105
#define IDC_BUTTON_ANIMATION_PLAY_FORWARD 1106
#define IDC_LOCK_ROTATION_Y             1106
#define IDC_BUTTON_ANIMATION_END        1107
#define IDC_LOCK_ROTATION_Z             1107
#define IDC_BUTTON_ANIMATION_STEP_BACKWARD 1108
#define IDC_LOCK_ZOOM                   1108
#define IDC_BUTTON_ANIMATION_PLAY_BACKWARD 1109
#define IDC_BUTTON_ANIMATION_START      1110
#define IDC_RADIO1                      1111
#define IDC_RADIO2                      1112
#define IDC_RADIO3                      1113
#define IDC_SLIDER_ANIMATION_TIMELINE   1114
#define IDC_CHECK2                      1115
#define IDC_CHECK_ENABLE_RESOURCE_MONITOR 1115
#define IDC_SLIDER_ANIMATION_TIME_MULTIPLIER 1118
#define IDC_ANIMATION_STEP_FORWARD      1119
#define IDC_ANIMATION_PLAY_FORWARD      1120
#define IDC_ANIMATION_STEP_BACKWARD     1121
#define IDC_ANIMATION_PLAY_BACKWARD     1122
#define IDC_EDIT_ANIMATION_MAX_TIME     1124
#define IDC_COMBO1                      1125
#define IDC_COMBO_SHADER_VERSION        1125
#define IDC_STATIC_OPTIONS_SHADER_VERSION 1126
#define IDC_STATIC_OPTIONS_RENDERING    1128
#define IDC_SLIDER_FOCUS_POINT_SIZE     1129
#define IDC_COMBO_GEOMETRY_QUALITY      1130
#define IDC_COMBO_TEXTURE_QUALITY       1133
#define IDC_BUTTON_SHADER_PATHS         1134
#define IDC_COLOUR_TYPEIN_COLOUR_INDICATOR 1135
#define IDC_STATIC_COPYRIGHT            1136
#define ID_FILE_EXIT                    32700
#define ID_NAVIGATION_RETURNTOORIGIN    32710
#define ID_NAVIGATION_VIEWPROPERTIES    32711
#define ID_DATA_AUTOCLEAR               32720
#define ID_DATA_NETWORKLISTENER         32721
#define ID_RENDERING_RIGHTHANDED        32730
#define ID_RENDERING_RENDER2D           32731
#define ID_WINDOW_ALWAYSONTOP           32740
#define ID_RENDERING_WIREFRAME          32741
#define ID_WINDOW_ABOUT                 32742
#define ID_ACCELERATOR_Console          32786
#define ID_ACCELERATOR_Open             32787
#define ID_ACCELERATOR_AdditiveOpen     32788
#define ID_ACCELERATOR_Save             32789
#define ID_ACCELERATOR_SaveAs           32790
#define ID_ACCELERATOR_RunPlugin        32791
#define ID_ACCELERATOR_InertialCamera   32792
#define ID_ACCELERATOR_Lighting         32793
#define ID_ACCELERATOR_Focus            32795
#define ID_INERTIALCAMERATYPE_OFF       32797
#define ID_NAVIGATION_ALIGNTO           32798
#define ID_ALIGNTO_X                    32799
#define ID_ALIGNTO_Y                    32800
#define ID_ALIGNTO_Z                    32801
#define ID_NAVIGATION_LOCK32802         32802
#define ID_RENDERING_CAMERAWANDER       32803
#define ID_INERTIALCAMERA_OFF           32804
#define ID_INERTIALCAMERA_FREECAMERA    32805
#define ID_INERTIALCAMERA_YLOCKEDCAMERA 32806
#define ID_FREECAMERA_OFF               32807
#define ID_FREECAMERA_FREECAMERA        32808
#define ID_FREECAMERA_YLOCKED           32809
#define ID_ACCELERATOR_Wireframe        32810
#define ID_DATA_SELECTNONE              32812
#define ID_RENDERING_DISABLERENDERING   32813
#define ID_ALIGNTO_SELECTED             32814
#define ID_ALIGNTO_SELECTED32815        32815
#define ID_DATA_PERSISTSTATE            32816
#define ID_FILE_LUA_CONSOLE             32817
#define ID_DATA_LISTENER                32818
#define ID_FILE_LDRCONSOLE              32819
#define ID_FILE_LDR_CONSOLE             32821
#define ID_ACCELERATOR_New              32822
#define ID_NAVIGATION_SELECTNEXT        32824
#define ID_NAVIGATION_SELECTPREV        32825
#define ID_DATA                         33000
#define ID_DATA_END                     33999
#define ID_AUTO_REFRESH_FROM_FILE       34000
#define ID_POLL_CAMERA                  34001
#define ID_STEP_PLUGIN                  34002
#define ID_REFRESH                      34003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        233
#define _APS_NEXT_COMMAND_VALUE         32826
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
