//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PhysicsTestbed.rc
//
#define IDD_DIALOG_CONTROLS             1000
#define IDC_BUTTON_SIM_RESET            1000
#define IDR_MENU1                       1001
#define IDC_BUTTON_SIM_GO               1001
#define IDC_BUTTON_SIM_STEP             1002
#define IDC_BUTTON_SIM_PAUSE            1003
#define IDD_DIALOG_SHAPE_GEN            1003
#define IDC_CHECK_STOP_OBJ_VS_OBJ       1007
#define IDC_EDIT_STOP_AT_FRAME          1008
#define IDC_EDIT_STEP_RATE              1009
#define IDC_CHECK_STOP_AT_FRAME         1010
#define IDC_CHECK_STOP_OBJ_VS_TERRAIN   1011
#define IDC_EDIT_STEP_SIZE              1012
#define IDC_EDIT_SEL_POSITION           1013
#define IDC_EDIT_SEL_VELOCITY           1014
#define IDC_EDIT_FRAME_NUM              1015
#define IDC_EDIT_SEL_ANG_VEL            1016
#define IDC_CHECK_SHOW_VELOCITY         1017
#define IDC_CHECK_SHOW_ANG_VELOCITY     1018
#define IDC_CHECK_SHOW_ANG_MOMENTUM     1019
#define IDC_CHECK_SHOW_COLLISION_IMPULSES 1020
#define IDC_EDIT_PHYS_OBJ_ADDR          1021
#define IDC_BUTTON_COLLISION_WATCH      1022
#define IDC_CHECK_SHOW_WS_BBOX          1023
#define IDC_CHECK_SHOW_CONTACTS         1024
#define IDC_BUTTON_VIEW_ALL             1025
#define IDC_EDIT_RANDOM_SEED            1026
#define IDC_SLIDER_COL_IMP_SCALE        1027
#define IDC_EDIT_FRAME_RATE             1028
#define IDC_SLIDER_STEP_RATE            1029
#define IDC_EDIT_SHAPE_GEN_CENTRE       1030
#define IDC_EDIT_OBJECT_COUNT           1030
#define IDC_CHECK_SHOW_BBOX2            1031
#define IDC_CHECK_SHOW_OS_BBOX          1031
#define IDC_CHECK_CHANGE_RANDSEED       1032
#define IDC_CHECK_SHOW_OS_BBOX2         1033
#define IDC_CHECK_SHOW_COM              1033
#define IDC_EDIT3                       1034
#define IDC_EDIT_SHAPE_GEN_RANGE        1034
#define IDC_CHECK_SHOW_COM2             1034
#define IDC_CHECK_SHOW_SLEEPING         1034
#define IDC_CHECK_SHOW_INERTIA          1035
#define IDC_EDIT_SHAPE_GEN_MIN_SIZE     1036
#define IDC_EDIT_SHAPE_GEN_BOX_MIN_DIMX 1036
#define IDC_EDIT_SHAPE_GEN_MAX_SIZE     1037
#define IDC_CHECK_SHOW_RESTING_CONTACTS 1037
#define IDC_EDIT_SHAPE_GEN_SPH_MIN_RADIUS 1038
#define IDC_EDIT_SHAPE_GEN_SPH_MAX_RADIUS 1039
#define IDC_EDIT_SHAPE_GEN_CYL_MIN_RADIUS 1042
#define IDC_EDIT_SHAPE_GEN_CYL_MAX_RADIUS 1043
#define IDC_EDIT_SHAPE_GEN_CYL_MIN_HEIGHT 1044
#define IDC_EDIT_SHAPE_GEN_CYL_MAX_HEIGHT 1045
#define IDC_EDIT_SHAPE_GEN_PLY_VCOUNT   1046
#define IDC_EDIT_SHAPE_GEN_BOX_MIN_DIMY 1049
#define IDC_EDIT_SHAPE_GEN_BOX_MIN_DIMZ 1050
#define IDC_EDIT_SHAPE_GEN_BOX_MAX_DIMX 1051
#define IDC_EDIT_SHAPE_GEN_BOX_MAX_DIMY 1052
#define IDC_EDIT_SHAPE_GEN_BOX_MAX_DIMZ 1053
#define IDC_EDIT_SHAPE_GEN_PLY_MIN_DIMX 1054
#define IDC_EDIT_SHAPE_GEN_PLY_MIN_DIMY 1055
#define IDC_EDIT_SHAPE_GEN_PLY_MIN_DIMZ 1056
#define IDC_EDIT_SHAPE_GEN_PLY_MAX_DIMX 1057
#define IDC_EDIT_SHAPE_GEN_PLY_MAX_DIMY 1058
#define IDC_EDIT_SHAPE_GEN_PLY_MAX_DIMZ 1059
#define ID_FILE_OPEN32771               32771
#define ID_FILE_EXIT                    32772
#define ID_OPTIONS_SHAPEGENERATION      32773
#define ID_FILE_EXPORT                  32774
#define ID_FILE_EXPORTAS                32775
#define ID_HELP_KEYCOMMANDS             32776
#define ID_OPTIONS_EXPORTEVERYFRAME     32777
#define ID_OPTIONS_TERRAINSAMPLER       32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1004
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
