#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU_MAIN                           101
#define IDR_ACCELERATOR                         102
#define IDI_ICON_MAIN                           103
#define IDD_DIALOG_MAIN                         111
#define IDD_DIALOG_OPTIONS                      112
#define IDD_TAB_GENERAL                         113
#define IDD_TAB_RENDERING                       114
#define IDD_TAB_NAVIGATION                      115
#define IDD_DIALOG_ABOUTBOX                     116
#define IDD_DIALOG_TEXT_ENTRY                   117
#define IDD_DIALOG_PLUGINS                      118
#define IDC_CHECK_RESET_CAM_ON_LOAD             1001
#define IDC_COMBO_GEOMETRY_QUALITY              1002
#define IDC_COMBO_SHADER_VERSION                1003
#define IDC_COMBO_TEXTURE_QUALITY               1004
#define IDC_EDIT_TEXT_EDITOR_CMD                1005
#define IDC_EDIT_ABOUT                          1006
#define IDC_EDIT_PLUGIN_FILEPATH                1007
#define IDC_EDIT_TEXT_ENTRY                     1008
#define IDC_EDIT_PLUGIN_ARGS                    1009
#define IDC_STATIC_CAM_ORBIT_SPEED              1010
#define IDC_CHECK_IGNORE_MISSING_INCLUDES       1011
#define IDC_CHECK_MSGBOX_ERROR_MSGS             1012
#define IDC_BUTTON_ADDPLUGIN                    1013
#define IDC_BUTTON_REMOVEPLUGIN                 1014
#define IDC_BUTTON_BROWSE_PLUGIN                1015
#define IDC_LBL_PLUGIN_DLL                      1016
#define IDC_LBL_PLUGIN_ARGS                     1017
#define IDC_STATIC_ERROR_OUTPUT                 1018
#define IDC_LIST_PLUGINS                        1019
#define IDC_SLIDER_CAM_ORBIT_SPEED              1020
#define IDC_SLIDER_FOCUS_POINT_SCALE            1021
#define IDC_TAB_MAIN                            1022
#define ID_FILE_NEW1                            40001
#define ID_FILE_NEWSCRIPT                       40002
#define ID_FILE_OPEN1                           40003
#define ID_FILE_ADDITIVEOPEN                    40004
#define ID_FILE_SAVE1                           40005
#define ID_FILE_SAVEAS                          40006
#define ID_FILE_RECENTFILES                     40007
#define ID_FILE_EXIT                            40018
#define ID_NAV_RESETVIEW_ALL                    40101
#define ID_NAV_RESETVIEW_SELECTED               40102
#define ID_NAV_RESETVIEW_VISIBLE                40103
#define ID_NAV_VIEW_AXIS_POSX                   40104
#define ID_NAV_VIEW_AXIS_NEGX                   40105
#define ID_NAV_VIEW_AXIS_POSY                   40106
#define ID_NAV_VIEW_AXIS_NEGY                   40107
#define ID_NAV_VIEW_AXIS_POSZ                   40108
#define ID_NAV_VIEW_AXIS_NEGZ                   40109
#define ID_NAV_VIEW_AXIS_POSXYZ                 40110
#define ID_NAV_SETFOCUSPOSITION                 40111
#define ID_NAV_SETCAMERAPOSITION                40112
#define ID_NAV_ALIGN_X                          40113
#define ID_NAV_ALIGN_Y                          40114
#define ID_NAV_ALIGN_Z                          40115
#define ID_NAV_ALIGN_CURRENT                    40116
#define ID_NAV_ALIGN_NONE                       40117
#define ID_NAV_CLEARSAVEDVIEWS                  40118
#define ID_NAV_SAVEVIEW                         40119
#define ID_NAV_SAVEDVIEWS                       40120
#define ID_NAV_ORBIT                            40131
#define ID_DATA_OBJECTMANAGER                   40201
#define ID_DATA_EDITSOURCEFILES                 40202
#define ID_DATA_CLEARSCENE                      40203
#define ID_DATA_AUTOREFRESH                     40204
#define ID_DATA_CREATE_DEMO_SCENE               40205
#define ID_RENDERING_SHOWFOCUS                  40301
#define ID_RENDERING_SHOWORIGIN                 40302
#define ID_RENDERING_SHOWSELECTION              40303
#define ID_RENDERING_SHOWOBJECTBBOXES           40304
#define ID_RENDERING_WIREFRAME                  40305
#define ID_RENDERING_RENDER2D                   40306
#define ID_RENDERING_TECHNIQUE                  40307
#define ID_RENDERING_LIGHTING                   40308
#define ID_TOOLS_MEASURE                        40401
#define ID_TOOLS_ANGLE                          40402
#define ID_TOOLS_PLUGINMGR                      40403
#define ID_TOOLS_OPTIONS                        40404
#define ID_WINDOW_ALWAYSONTOP                   40501
#define ID_WINDOW_BACKGROUNDCOLOUR              40502
#define ID_WINDOW_EXAMPLESCRIPT                 40503
#define ID_WINDOW_CHECKFORUPDATES               40504
#define ID_WINDOW_ABOUTLINEDRAWER               40505
#define ID_ACCELERATOR_FILENEW                  40601
#define ID_ACCELERATOR_FILENEWSCRIPT            40602
#define ID_ACCELERATOR_FILEOPEN                 40603
#define ID_ACCELERATOR_FILEOPEN_ADDITIVE        40604
#define ID_ACCELERATOR_EDITOR                   40605
#define ID_ACCELERATOR_CAMERAPOS                40606
#define ID_ACCELERATOR_PLUGINMGR                40607
#define ID_ACCELERATOR_WIREFRAME                40608
#define ID_ACCELERATOR_LIGHTING_DLG             40609
#define ID_ACCELERATOR_UNDO                     40610
#define ID_ACCELERATOR_REDO                     40611
