#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG_MAIN                         101
#define IDR_MENU_MAIN                           102
#define IDI_ICON_MAIN                           103
#define IDD_DIALOG_OPTIONS                      107
#define IDD_TAB_GENERAL                         108
#define IDD_TAB_RENDERING                       109
#define IDD_TAB_NAVIGATION                      110
#define IDD_DIALOG_ABOUTBOX                     111
#define IDD_DIALOG_TEXT_ENTRY                   113
#define IDD_DIALOG_PLUGINS                      114
#define IDR_ACCELERATOR                         115
#define IDC_CHECK_RESET_CAM_ON_LOAD             1004
#define IDC_COMBO_GEOMETRY_QUALITY              1005
#define IDC_COMBO_SHADER_VERSION                1006
#define IDC_COMBO_TEXTURE_QUALITY               1007
#define IDC_EDIT_TEXT_EDITOR_CMD                1008
#define IDC_EDIT_ABOUT                          1009
#define IDC_EDIT_PLUGIN_FILEPATH                1013
#define IDC_EDIT_TEXT_ENTRY                     1013
#define IDC_EDIT_PLUGIN_ARGS                    1014
#define IDC_STATIC_CAM_ORBIT_SPEED              1015
#define IDC_CHECK_IGNORE_MISSING_INCLUDES       1016
#define IDC_CHECK_MSGBOX_ERROR_MSGS             1017
#define IDC_BUTTON_ADDPLUGIN                    1019
#define IDC_BUTTON_REMOVEPLUGIN                 1020
#define IDC_BUTTON_BROWSE_PLUGIN                1021
#define IDC_LBL_PLUGIN_DLL                      1022
#define IDC_LBL_PLUGIN_ARGS                     1023
#define ID_NAVIGATION_SAVEDVIEWS                39100
#define IDC_STATIC_ERROR_OUTPUT                 40000
#define ID_ACCELERATOR_FILENEWSCRIPT            40000
#define ID_FILE_RECENTFILES                     40000
#define ID_ACCELERATOR_UNDO                     40001
#define IDC_LIST_PLUGINS                        40002
#define IDC_SLIDER_CAM_ORBIT_SPEED              40002
#define IDC_SLIDER_FOCUS_POINT_SCALE            40002
#define IDC_TAB_MAIN                            40002
#define ID_ACCELERATOR_REDO                     40002
#define ID_FILE_NEW1                            40002
#define ID_FILE_NEWSCRIPT                       40003
#define ID_FILE_OPEN1                           40004
#define ID_FILE_ADDITIVEOPEN                    40005
#define ID_FILE_SAVE1                           40006
#define ID_FILE_SAVEAS                          40007
#define ID_FILE_OPTIONS                         40008
#define ID_FILE_EXIT                            40009
#define ID_RENDERING_SHOWFOCUS                  40013
#define ID_RENDERING_LIGHTING                   40015
#define ID_DATA_CREATE_DEMO_SCENE               40017
#define ID_DATA_OBJECTMANAGER                   40018
#define ID_NAV_RESETVIEW_ALL                    40022
#define ID_NAV_RESETVIEW_SELECTED               40023
#define ID_NAV_RESETVIEW_VISIBLE                40025
#define ID_RENDERING_SHOWORIGIN                 40026
#define ID_DATA_CLEARSCENE                      40027
#define ID_ACCELERATOR_FILEOPEN                 40028
#define ID_ACCELERATOR_FILEOPEN_ADDITIVE        40029
#define ID_ACCELERATOR_WIREFRAME                40030
#define ID_RENDERING_WIREFRAME                  40032
#define ID_NAV_ALIGN_X                          40038
#define ID_NAV_ALIGN_Y                          40039
#define ID_NAV_ALIGN_Z                          40040
#define ID_NAV_ALIGN_NONE                       40041
#define ID_DATA_EDITSOURCEFILES                 40042
#define ID_RENDERING_RENDER2D                   40043
#define ID_WINDOW_ALWAYSONTOP                   40045
#define ID_WINDOW_BACKGROUNDCOLOUR              40046
#define ID_WINDOW_ABOUTLINEDRAWER               40047
#define ID_VIEW_AXIS_POSX                       40057
#define ID_VIEW_AXIS_NEGX                       40058
#define ID_VIEW_AXIS_POSY                       40059
#define ID_VIEW_AXIS_NEGY                       40060
#define ID_VIEW_AXIS_POSZ                       40061
#define ID_VIEW_AXIS_NEGZ                       40062
#define ID_VIEW_AXIS_POSXYZ                     40063
#define ID_RENDERING_SHOWSELECTION              40065
#define ID_DATA_AUTOREFRESH                     40066
#define ID_WINDOW_EXAMPLESCRIPT                 40067
#define ID_RENDERING_SHOWOBJECTBBOXES           40068
#define ID_NAVIGATION_ORBIT                     40069
#define ID_NAVIGATION_SETFOCUSPOSITION          40071
#define ID_ACCELERATOR_EDITOR                   40072
#define ID_NAVIGATION_SAVEVIEW                  40077
#define ID_NAVIGATION_CLEARSAVEDVIEWS           40079
#define ID_NAV_ALIGN_CURRENT                    40081
#define ID_TOOLS_MEASURE                        40082
#define ID_FILE_PLUGINMGR                       40083
#define ID_ACCELERATOR_PLUGINMGR                40084
#define ID_TOOLS_ANGLE                          40086
#define ID_ACCELERATOR_FILENEW                  40087
#define ID_ACCELERATOR_LIGHTING_DLG             40089
#define ID_WINDOW_CHECKFORUPDATES               40090
