/* Scintilla source code edit control */
/** @file Scintilla.h
 ** Interface to the edit control.
 **/
/* Copyright 1998-2003 by Neil Hodgson <neilh@scintilla.org>
 * The License.txt file describes the conditions under which this software may be distributed. */

/* Most of this file is automatically generated from the Scintilla.iface interface definition
 * file which contains any comments about the definitions. HFacer.py does the generation. */

#ifndef SCINTILLA_H
#define SCINTILLA_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined(_WIN32)
/* Return false on failure: */
int Scintilla_RegisterClasses(void *hInstance);
int Scintilla_ReleaseResources(void);
#endif

#ifdef __cplusplus
}
#endif

// Include header that defines basic numeric types.
#include <stdint.h>

// Define uptr_t, an unsigned integer type large enough to hold a pointer.
typedef uintptr_t uptr_t;
// Define sptr_t, a signed integer large enough to hold a pointer.
typedef intptr_t sptr_t;

#include "Sci_Position.h"

typedef sptr_t (*SciFnDirect)(sptr_t ptr, unsigned int iMessage, uptr_t wParam, sptr_t lParam);
typedef sptr_t (*SciFnDirectStatus)(sptr_t ptr, unsigned int iMessage, uptr_t wParam, sptr_t lParam, int *pStatus);

#ifndef SCI_DISABLE_AUTOGENERATED

/* ++Autogenerated -- start of section automatically generated from Scintilla.iface */
#pragma region SCI Constants
constexpr int INVALID_POSITION = -1;
constexpr int SCI_START = 2000;
constexpr int SCI_OPTIONAL_START = 3000;
constexpr int SCI_LEXER_START = 4000;
constexpr int SCI_ADDTEXT = 2001;
constexpr int SCI_ADDSTYLEDTEXT = 2002;
constexpr int SCI_INSERTTEXT = 2003;
constexpr int SCI_CHANGEINSERTION = 2672;
constexpr int SCI_CLEARALL = 2004;
constexpr int SCI_DELETERANGE = 2645;
constexpr int SCI_CLEARDOCUMENTSTYLE = 2005;
constexpr int SCI_GETLENGTH = 2006;
constexpr int SCI_GETCHARAT = 2007;
constexpr int SCI_GETCURRENTPOS = 2008;
constexpr int SCI_GETANCHOR = 2009;
constexpr int SCI_GETSTYLEAT = 2010;
constexpr int SCI_GETSTYLEINDEXAT = 2038;
constexpr int SCI_REDO = 2011;
constexpr int SCI_SETUNDOCOLLECTION = 2012;
constexpr int SCI_SELECTALL = 2013;
constexpr int SCI_SETSAVEPOINT = 2014;
constexpr int SCI_GETSTYLEDTEXT = 2015;
constexpr int SCI_CANREDO = 2016;
constexpr int SCI_MARKERLINEFROMHANDLE = 2017;
constexpr int SCI_MARKERDELETEHANDLE = 2018;
constexpr int SCI_MARKERHANDLEFROMLINE = 2732;
constexpr int SCI_MARKERNUMBERFROMLINE = 2733;
constexpr int SCI_GETUNDOCOLLECTION = 2019;
constexpr int SCWS_INVISIBLE = 0;
constexpr int SCWS_VISIBLEALWAYS = 1;
constexpr int SCWS_VISIBLEAFTERINDENT = 2;
constexpr int SCWS_VISIBLEONLYININDENT = 3;
constexpr int SCI_GETVIEWWS = 2020;
constexpr int SCI_SETVIEWWS = 2021;
constexpr int SCTD_LONGARROW = 0;
constexpr int SCTD_STRIKEOUT = 1;
constexpr int SCI_GETTABDRAWMODE = 2698;
constexpr int SCI_SETTABDRAWMODE = 2699;
constexpr int SCI_POSITIONFROMPOINT = 2022;
constexpr int SCI_POSITIONFROMPOINTCLOSE = 2023;
constexpr int SCI_GOTOLINE = 2024;
constexpr int SCI_GOTOPOS = 2025;
constexpr int SCI_SETANCHOR = 2026;
constexpr int SCI_GETCURLINE = 2027;
constexpr int SCI_GETENDSTYLED = 2028;
constexpr int SC_EOL_CRLF = 0;
constexpr int SC_EOL_CR = 1;
constexpr int SC_EOL_LF = 2;
constexpr int SCI_CONVERTEOLS = 2029;
constexpr int SCI_GETEOLMODE = 2030;
constexpr int SCI_SETEOLMODE = 2031;
constexpr int SCI_STARTSTYLING = 2032;
constexpr int SCI_SETSTYLING = 2033;
constexpr int SCI_GETBUFFEREDDRAW = 2034;
constexpr int SCI_SETBUFFEREDDRAW = 2035;
constexpr int SCI_SETTABWIDTH = 2036;
constexpr int SCI_GETTABWIDTH = 2121;
constexpr int SCI_SETTABMINIMUMWIDTH = 2724;
constexpr int SCI_GETTABMINIMUMWIDTH = 2725;
constexpr int SCI_CLEARTABSTOPS = 2675;
constexpr int SCI_ADDTABSTOP = 2676;
constexpr int SCI_GETNEXTTABSTOP = 2677;
constexpr int SC_CP_UTF8 = 65001;
constexpr int SCI_SETCODEPAGE = 2037;
constexpr int SCI_SETFONTLOCALE = 2760;
constexpr int SCI_GETFONTLOCALE = 2761;
constexpr int SC_IME_WINDOWED = 0;
constexpr int SC_IME_INLINE = 1;
constexpr int SCI_GETIMEINTERACTION = 2678;
constexpr int SCI_SETIMEINTERACTION = 2679;
constexpr int SC_ALPHA_TRANSPARENT = 0;
constexpr int SC_ALPHA_OPAQUE = 255;
constexpr int SC_ALPHA_NOALPHA = 256;
constexpr int SC_CURSORNORMAL = -1;
constexpr int SC_CURSORARROW = 2;
constexpr int SC_CURSORWAIT = 4;
constexpr int SC_CURSORREVERSEARROW = 7;
constexpr int MARKER_MAX = 31;
constexpr int SC_MARK_CIRCLE = 0;
constexpr int SC_MARK_ROUNDRECT = 1;
constexpr int SC_MARK_ARROW = 2;
constexpr int SC_MARK_SMALLRECT = 3;
constexpr int SC_MARK_SHORTARROW = 4;
constexpr int SC_MARK_EMPTY = 5;
constexpr int SC_MARK_ARROWDOWN = 6;
constexpr int SC_MARK_MINUS = 7;
constexpr int SC_MARK_PLUS = 8;
constexpr int SC_MARK_VLINE = 9;
constexpr int SC_MARK_LCORNER = 10;
constexpr int SC_MARK_TCORNER = 11;
constexpr int SC_MARK_BOXPLUS = 12;
constexpr int SC_MARK_BOXPLUSCONNECTED = 13;
constexpr int SC_MARK_BOXMINUS = 14;
constexpr int SC_MARK_BOXMINUSCONNECTED = 15;
constexpr int SC_MARK_LCORNERCURVE = 16;
constexpr int SC_MARK_TCORNERCURVE = 17;
constexpr int SC_MARK_CIRCLEPLUS = 18;
constexpr int SC_MARK_CIRCLEPLUSCONNECTED = 19;
constexpr int SC_MARK_CIRCLEMINUS = 20;
constexpr int SC_MARK_CIRCLEMINUSCONNECTED = 21;
constexpr int SC_MARK_BACKGROUND = 22;
constexpr int SC_MARK_DOTDOTDOT = 23;
constexpr int SC_MARK_ARROWS = 24;
constexpr int SC_MARK_PIXMAP = 25;
constexpr int SC_MARK_FULLRECT = 26;
constexpr int SC_MARK_LEFTRECT = 27;
constexpr int SC_MARK_AVAILABLE = 28;
constexpr int SC_MARK_UNDERLINE = 29;
constexpr int SC_MARK_RGBAIMAGE = 30;
constexpr int SC_MARK_BOOKMARK = 31;
constexpr int SC_MARK_VERTICALBOOKMARK = 32;
constexpr int SC_MARK_BAR = 33;
constexpr int SC_MARK_CHARACTER = 10000;
constexpr int SC_MARKNUM_HISTORY_REVERTED_TO_ORIGIN = 21;
constexpr int SC_MARKNUM_HISTORY_SAVED = 22;
constexpr int SC_MARKNUM_HISTORY_MODIFIED = 23;
constexpr int SC_MARKNUM_HISTORY_REVERTED_TO_MODIFIED = 24;
constexpr int SC_MARKNUM_FOLDEREND = 25;
constexpr int SC_MARKNUM_FOLDEROPENMID = 26;
constexpr int SC_MARKNUM_FOLDERMIDTAIL = 27;
constexpr int SC_MARKNUM_FOLDERTAIL = 28;
constexpr int SC_MARKNUM_FOLDERSUB = 29;
constexpr int SC_MARKNUM_FOLDER = 30;
constexpr int SC_MARKNUM_FOLDEROPEN = 31;
constexpr int SC_MASK_FOLDERS = 0xFE000000;
constexpr int SCI_MARKERDEFINE = 2040;
constexpr int SCI_MARKERSETFORE = 2041;
constexpr int SCI_MARKERSETBACK = 2042;
constexpr int SCI_MARKERSETBACKSELECTED = 2292;
constexpr int SCI_MARKERSETFORETRANSLUCENT = 2294;
constexpr int SCI_MARKERSETBACKTRANSLUCENT = 2295;
constexpr int SCI_MARKERSETBACKSELECTEDTRANSLUCENT = 2296;
constexpr int SCI_MARKERSETSTROKEWIDTH = 2297;
constexpr int SCI_MARKERENABLEHIGHLIGHT = 2293;
constexpr int SCI_MARKERADD = 2043;
constexpr int SCI_MARKERDELETE = 2044;
constexpr int SCI_MARKERDELETEALL = 2045;
constexpr int SCI_MARKERGET = 2046;
constexpr int SCI_MARKERNEXT = 2047;
constexpr int SCI_MARKERPREVIOUS = 2048;
constexpr int SCI_MARKERDEFINEPIXMAP = 2049;
constexpr int SCI_MARKERADDSET = 2466;
constexpr int SCI_MARKERSETALPHA = 2476;
constexpr int SCI_MARKERGETLAYER = 2734;
constexpr int SCI_MARKERSETLAYER = 2735;
constexpr int SC_MAX_MARGIN = 4;
constexpr int SC_MARGIN_SYMBOL = 0;
constexpr int SC_MARGIN_NUMBER = 1;
constexpr int SC_MARGIN_BACK = 2;
constexpr int SC_MARGIN_FORE = 3;
constexpr int SC_MARGIN_TEXT = 4;
constexpr int SC_MARGIN_RTEXT = 5;
constexpr int SC_MARGIN_COLOUR = 6;
constexpr int SCI_SETMARGINTYPEN = 2240;
constexpr int SCI_GETMARGINTYPEN = 2241;
constexpr int SCI_SETMARGINWIDTHN = 2242;
constexpr int SCI_GETMARGINWIDTHN = 2243;
constexpr int SCI_SETMARGINMASKN = 2244;
constexpr int SCI_GETMARGINMASKN = 2245;
constexpr int SCI_SETMARGINSENSITIVEN = 2246;
constexpr int SCI_GETMARGINSENSITIVEN = 2247;
constexpr int SCI_SETMARGINCURSORN = 2248;
constexpr int SCI_GETMARGINCURSORN = 2249;
constexpr int SCI_SETMARGINBACKN = 2250;
constexpr int SCI_GETMARGINBACKN = 2251;
constexpr int SCI_SETMARGINS = 2252;
constexpr int SCI_GETMARGINS = 2253;
constexpr int STYLE_DEFAULT = 32;
constexpr int STYLE_LINENUMBER = 33;
constexpr int STYLE_BRACELIGHT = 34;
constexpr int STYLE_BRACEBAD = 35;
constexpr int STYLE_CONTROLCHAR = 36;
constexpr int STYLE_INDENTGUIDE = 37;
constexpr int STYLE_CALLTIP = 38;
constexpr int STYLE_FOLDDISPLAYTEXT = 39;
constexpr int STYLE_LASTPREDEFINED = 39;
constexpr int STYLE_MAX = 255;
constexpr int SC_CHARSET_ANSI = 0;
constexpr int SC_CHARSET_DEFAULT = 1;
constexpr int SC_CHARSET_BALTIC = 186;
constexpr int SC_CHARSET_CHINESEBIG5 = 136;
constexpr int SC_CHARSET_EASTEUROPE = 238;
constexpr int SC_CHARSET_GB2312 = 134;
constexpr int SC_CHARSET_GREEK = 161;
constexpr int SC_CHARSET_HANGUL = 129;
constexpr int SC_CHARSET_MAC = 77;
constexpr int SC_CHARSET_OEM = 255;
constexpr int SC_CHARSET_RUSSIAN = 204;
constexpr int SC_CHARSET_OEM866 = 866;
constexpr int SC_CHARSET_CYRILLIC = 1251;
constexpr int SC_CHARSET_SHIFTJIS = 128;
constexpr int SC_CHARSET_SYMBOL = 2;
constexpr int SC_CHARSET_TURKISH = 162;
constexpr int SC_CHARSET_JOHAB = 130;
constexpr int SC_CHARSET_HEBREW = 177;
constexpr int SC_CHARSET_ARABIC = 178;
constexpr int SC_CHARSET_VIETNAMESE = 163;
constexpr int SC_CHARSET_THAI = 222;
constexpr int SC_CHARSET_8859_15 = 1000;
constexpr int SCI_STYLECLEARALL = 2050;
constexpr int SCI_STYLESETFORE = 2051;
constexpr int SCI_STYLESETBACK = 2052;
constexpr int SCI_STYLESETBOLD = 2053;
constexpr int SCI_STYLESETITALIC = 2054;
constexpr int SCI_STYLESETSIZE = 2055;
constexpr int SCI_STYLESETFONT = 2056;
constexpr int SCI_STYLESETEOLFILLED = 2057;
constexpr int SCI_STYLERESETDEFAULT = 2058;
constexpr int SCI_STYLESETUNDERLINE = 2059;
constexpr int SC_CASE_MIXED = 0;
constexpr int SC_CASE_UPPER = 1;
constexpr int SC_CASE_LOWER = 2;
constexpr int SC_CASE_CAMEL = 3;
constexpr int SCI_STYLEGETFORE = 2481;
constexpr int SCI_STYLEGETBACK = 2482;
constexpr int SCI_STYLEGETBOLD = 2483;
constexpr int SCI_STYLEGETITALIC = 2484;
constexpr int SCI_STYLEGETSIZE = 2485;
constexpr int SCI_STYLEGETFONT = 2486;
constexpr int SCI_STYLEGETEOLFILLED = 2487;
constexpr int SCI_STYLEGETUNDERLINE = 2488;
constexpr int SCI_STYLEGETCASE = 2489;
constexpr int SCI_STYLEGETCHARACTERSET = 2490;
constexpr int SCI_STYLEGETVISIBLE = 2491;
constexpr int SCI_STYLEGETCHANGEABLE = 2492;
constexpr int SCI_STYLEGETHOTSPOT = 2493;
constexpr int SCI_STYLESETCASE = 2060;
constexpr int SC_FONT_SIZE_MULTIPLIER = 100;
constexpr int SCI_STYLESETSIZEFRACTIONAL = 2061;
constexpr int SCI_STYLEGETSIZEFRACTIONAL = 2062;
constexpr int SC_WEIGHT_NORMAL = 400;
constexpr int SC_WEIGHT_SEMIBOLD = 600;
constexpr int SC_WEIGHT_BOLD = 700;
constexpr int SCI_STYLESETWEIGHT = 2063;
constexpr int SCI_STYLEGETWEIGHT = 2064;
constexpr int SCI_STYLESETCHARACTERSET = 2066;
constexpr int SCI_STYLESETHOTSPOT = 2409;
constexpr int SCI_STYLESETCHECKMONOSPACED = 2254;
constexpr int SCI_STYLEGETCHECKMONOSPACED = 2255;
constexpr int SC_ELEMENT_LIST = 0;
constexpr int SC_ELEMENT_LIST_BACK = 1;
constexpr int SC_ELEMENT_LIST_SELECTED = 2;
constexpr int SC_ELEMENT_LIST_SELECTED_BACK = 3;
constexpr int SC_ELEMENT_SELECTION_TEXT = 10;
constexpr int SC_ELEMENT_SELECTION_BACK = 11;
constexpr int SC_ELEMENT_SELECTION_ADDITIONAL_TEXT = 12;
constexpr int SC_ELEMENT_SELECTION_ADDITIONAL_BACK = 13;
constexpr int SC_ELEMENT_SELECTION_SECONDARY_TEXT = 14;
constexpr int SC_ELEMENT_SELECTION_SECONDARY_BACK = 15;
constexpr int SC_ELEMENT_SELECTION_INACTIVE_TEXT = 16;
constexpr int SC_ELEMENT_SELECTION_INACTIVE_BACK = 17;
constexpr int SC_ELEMENT_CARET = 40;
constexpr int SC_ELEMENT_CARET_ADDITIONAL = 41;
constexpr int SC_ELEMENT_CARET_LINE_BACK = 50;
constexpr int SC_ELEMENT_WHITE_SPACE = 60;
constexpr int SC_ELEMENT_WHITE_SPACE_BACK = 61;
constexpr int SC_ELEMENT_HOT_SPOT_ACTIVE = 70;
constexpr int SC_ELEMENT_HOT_SPOT_ACTIVE_BACK = 71;
constexpr int SC_ELEMENT_FOLD_LINE = 80;
constexpr int SC_ELEMENT_HIDDEN_LINE = 81;
constexpr int SCI_SETELEMENTCOLOUR = 2753;
constexpr int SCI_GETELEMENTCOLOUR = 2754;
constexpr int SCI_RESETELEMENTCOLOUR = 2755;
constexpr int SCI_GETELEMENTISSET = 2756;
constexpr int SCI_GETELEMENTALLOWSTRANSLUCENT = 2757;
constexpr int SCI_GETELEMENTBASECOLOUR = 2758;
constexpr int SCI_SETSELFORE = 2067;
constexpr int SCI_SETSELBACK = 2068;
constexpr int SCI_GETSELALPHA = 2477;
constexpr int SCI_SETSELALPHA = 2478;
constexpr int SCI_GETSELEOLFILLED = 2479;
constexpr int SCI_SETSELEOLFILLED = 2480;
constexpr int SC_LAYER_BASE = 0;
constexpr int SC_LAYER_UNDER_TEXT = 1;
constexpr int SC_LAYER_OVER_TEXT = 2;
constexpr int SCI_GETSELECTIONLAYER = 2762;
constexpr int SCI_SETSELECTIONLAYER = 2763;
constexpr int SCI_GETCARETLINELAYER = 2764;
constexpr int SCI_SETCARETLINELAYER = 2765;
constexpr int SCI_GETCARETLINEHIGHLIGHTSUBLINE = 2773;
constexpr int SCI_SETCARETLINEHIGHLIGHTSUBLINE = 2774;
constexpr int SCI_SETCARETFORE = 2069;
constexpr int SCI_ASSIGNCMDKEY = 2070;
constexpr int SCI_CLEARCMDKEY = 2071;
constexpr int SCI_CLEARALLCMDKEYS = 2072;
constexpr int SCI_SETSTYLINGEX = 2073;
constexpr int SCI_STYLESETVISIBLE = 2074;
constexpr int SCI_GETCARETPERIOD = 2075;
constexpr int SCI_SETCARETPERIOD = 2076;
constexpr int SCI_SETWORDCHARS = 2077;
constexpr int SCI_GETWORDCHARS = 2646;
constexpr int SCI_SETCHARACTERCATEGORYOPTIMIZATION = 2720;
constexpr int SCI_GETCHARACTERCATEGORYOPTIMIZATION = 2721;
constexpr int SCI_BEGINUNDOACTION = 2078;
constexpr int SCI_ENDUNDOACTION = 2079;
constexpr int INDIC_PLAIN = 0;
constexpr int INDIC_SQUIGGLE = 1;
constexpr int INDIC_TT = 2;
constexpr int INDIC_DIAGONAL = 3;
constexpr int INDIC_STRIKE = 4;
constexpr int INDIC_HIDDEN = 5;
constexpr int INDIC_BOX = 6;
constexpr int INDIC_ROUNDBOX = 7;
constexpr int INDIC_STRAIGHTBOX = 8;
constexpr int INDIC_DASH = 9;
constexpr int INDIC_DOTS = 10;
constexpr int INDIC_SQUIGGLELOW = 11;
constexpr int INDIC_DOTBOX = 12;
constexpr int INDIC_SQUIGGLEPIXMAP = 13;
constexpr int INDIC_COMPOSITIONTHICK = 14;
constexpr int INDIC_COMPOSITIONTHIN = 15;
constexpr int INDIC_FULLBOX = 16;
constexpr int INDIC_TEXTFORE = 17;
constexpr int INDIC_POINT = 18;
constexpr int INDIC_POINTCHARACTER = 19;
constexpr int INDIC_GRADIENT = 20;
constexpr int INDIC_GRADIENTCENTRE = 21;
constexpr int INDIC_POINT_TOP = 22;
constexpr int INDIC_CONTAINER = 8;
constexpr int INDIC_IME = 32;
constexpr int INDIC_IME_MAX = 35;
constexpr int INDIC_MAX = 35;
constexpr int INDICATOR_CONTAINER = 8;
constexpr int INDICATOR_IME = 32;
constexpr int INDICATOR_IME_MAX = 35;
constexpr int INDICATOR_HISTORY_REVERTED_TO_ORIGIN_INSERTION = 36;
constexpr int INDICATOR_HISTORY_REVERTED_TO_ORIGIN_DELETION = 37;
constexpr int INDICATOR_HISTORY_SAVED_INSERTION = 38;
constexpr int INDICATOR_HISTORY_SAVED_DELETION = 39;
constexpr int INDICATOR_HISTORY_MODIFIED_INSERTION = 40;
constexpr int INDICATOR_HISTORY_MODIFIED_DELETION = 41;
constexpr int INDICATOR_HISTORY_REVERTED_TO_MODIFIED_INSERTION = 42;
constexpr int INDICATOR_HISTORY_REVERTED_TO_MODIFIED_DELETION = 43;
constexpr int INDICATOR_MAX = 43;
constexpr int SCI_INDICSETSTYLE = 2080;
constexpr int SCI_INDICGETSTYLE = 2081;
constexpr int SCI_INDICSETFORE = 2082;
constexpr int SCI_INDICGETFORE = 2083;
constexpr int SCI_INDICSETUNDER = 2510;
constexpr int SCI_INDICGETUNDER = 2511;
constexpr int SCI_INDICSETHOVERSTYLE = 2680;
constexpr int SCI_INDICGETHOVERSTYLE = 2681;
constexpr int SCI_INDICSETHOVERFORE = 2682;
constexpr int SCI_INDICGETHOVERFORE = 2683;
constexpr int SC_INDICVALUEBIT = 0x1000000;
constexpr int SC_INDICVALUEMASK = 0xFFFFFF;
constexpr int SC_INDICFLAG_NONE = 0;
constexpr int SC_INDICFLAG_VALUEFORE = 1;
constexpr int SCI_INDICSETFLAGS = 2684;
constexpr int SCI_INDICGETFLAGS = 2685;
constexpr int SCI_INDICSETSTROKEWIDTH = 2751;
constexpr int SCI_INDICGETSTROKEWIDTH = 2752;
constexpr int SCI_SETWHITESPACEFORE = 2084;
constexpr int SCI_SETWHITESPACEBACK = 2085;
constexpr int SCI_SETWHITESPACESIZE = 2086;
constexpr int SCI_GETWHITESPACESIZE = 2087;
constexpr int SCI_SETLINESTATE = 2092;
constexpr int SCI_GETLINESTATE = 2093;
constexpr int SCI_GETMAXLINESTATE = 2094;
constexpr int SCI_GETCARETLINEVISIBLE = 2095;
constexpr int SCI_SETCARETLINEVISIBLE = 2096;
constexpr int SCI_GETCARETLINEBACK = 2097;
constexpr int SCI_SETCARETLINEBACK = 2098;
constexpr int SCI_GETCARETLINEFRAME = 2704;
constexpr int SCI_SETCARETLINEFRAME = 2705;
constexpr int SCI_STYLESETCHANGEABLE = 2099;
constexpr int SCI_AUTOCSHOW = 2100;
constexpr int SCI_AUTOCCANCEL = 2101;
constexpr int SCI_AUTOCACTIVE = 2102;
constexpr int SCI_AUTOCPOSSTART = 2103;
constexpr int SCI_AUTOCCOMPLETE = 2104;
constexpr int SCI_AUTOCSTOPS = 2105;
constexpr int SCI_AUTOCSETSEPARATOR = 2106;
constexpr int SCI_AUTOCGETSEPARATOR = 2107;
constexpr int SCI_AUTOCSELECT = 2108;
constexpr int SCI_AUTOCSETCANCELATSTART = 2110;
constexpr int SCI_AUTOCGETCANCELATSTART = 2111;
constexpr int SCI_AUTOCSETFILLUPS = 2112;
constexpr int SCI_AUTOCSETCHOOSESINGLE = 2113;
constexpr int SCI_AUTOCGETCHOOSESINGLE = 2114;
constexpr int SCI_AUTOCSETIGNORECASE = 2115;
constexpr int SCI_AUTOCGETIGNORECASE = 2116;
constexpr int SCI_USERLISTSHOW = 2117;
constexpr int SCI_AUTOCSETAUTOHIDE = 2118;
constexpr int SCI_AUTOCGETAUTOHIDE = 2119;
constexpr int SC_AUTOCOMPLETE_NORMAL = 0;
constexpr int SC_AUTOCOMPLETE_FIXED_SIZE = 1;
constexpr int SCI_AUTOCSETOPTIONS = 2638;
constexpr int SCI_AUTOCGETOPTIONS = 2639;
constexpr int SCI_AUTOCSETDROPRESTOFWORD = 2270;
constexpr int SCI_AUTOCGETDROPRESTOFWORD = 2271;
constexpr int SCI_REGISTERIMAGE = 2405;
constexpr int SCI_CLEARREGISTEREDIMAGES = 2408;
constexpr int SCI_AUTOCGETTYPESEPARATOR = 2285;
constexpr int SCI_AUTOCSETTYPESEPARATOR = 2286;
constexpr int SCI_AUTOCSETMAXWIDTH = 2208;
constexpr int SCI_AUTOCGETMAXWIDTH = 2209;
constexpr int SCI_AUTOCSETMAXHEIGHT = 2210;
constexpr int SCI_AUTOCGETMAXHEIGHT = 2211;
constexpr int SCI_SETINDENT = 2122;
constexpr int SCI_GETINDENT = 2123;
constexpr int SCI_SETUSETABS = 2124;
constexpr int SCI_GETUSETABS = 2125;
constexpr int SCI_SETLINEINDENTATION = 2126;
constexpr int SCI_GETLINEINDENTATION = 2127;
constexpr int SCI_GETLINEINDENTPOSITION = 2128;
constexpr int SCI_GETCOLUMN = 2129;
constexpr int SCI_COUNTCHARACTERS = 2633;
constexpr int SCI_COUNTCODEUNITS = 2715;
constexpr int SCI_SETHSCROLLBAR = 2130;
constexpr int SCI_GETHSCROLLBAR = 2131;
constexpr int SC_IV_NONE = 0;
constexpr int SC_IV_REAL = 1;
constexpr int SC_IV_LOOKFORWARD = 2;
constexpr int SC_IV_LOOKBOTH = 3;
constexpr int SCI_SETINDENTATIONGUIDES = 2132;
constexpr int SCI_GETINDENTATIONGUIDES = 2133;
constexpr int SCI_SETHIGHLIGHTGUIDE = 2134;
constexpr int SCI_GETHIGHLIGHTGUIDE = 2135;
constexpr int SCI_GETLINEENDPOSITION = 2136;
constexpr int SCI_GETCODEPAGE = 2137;
constexpr int SCI_GETCARETFORE = 2138;
constexpr int SCI_GETREADONLY = 2140;
constexpr int SCI_SETCURRENTPOS = 2141;
constexpr int SCI_SETSELECTIONSTART = 2142;
constexpr int SCI_GETSELECTIONSTART = 2143;
constexpr int SCI_SETSELECTIONEND = 2144;
constexpr int SCI_GETSELECTIONEND = 2145;
constexpr int SCI_SETEMPTYSELECTION = 2556;
constexpr int SCI_SETPRINTMAGNIFICATION = 2146;
constexpr int SCI_GETPRINTMAGNIFICATION = 2147;
constexpr int SC_PRINT_NORMAL = 0;
constexpr int SC_PRINT_INVERTLIGHT = 1;
constexpr int SC_PRINT_BLACKONWHITE = 2;
constexpr int SC_PRINT_COLOURONWHITE = 3;
constexpr int SC_PRINT_COLOURONWHITEDEFAULTBG = 4;
constexpr int SC_PRINT_SCREENCOLOURS = 5;
constexpr int SCI_SETPRINTCOLOURMODE = 2148;
constexpr int SCI_GETPRINTCOLOURMODE = 2149;
constexpr int SCFIND_NONE = 0x0;
constexpr int SCFIND_WHOLEWORD = 0x2;
constexpr int SCFIND_MATCHCASE = 0x4;
constexpr int SCFIND_WORDSTART = 0x00100000;
constexpr int SCFIND_REGEXP = 0x00200000;
constexpr int SCFIND_POSIX = 0x00400000;
constexpr int SCFIND_CXX11REGEX = 0x00800000;
constexpr int SCI_FINDTEXT = 2150;
constexpr int SCI_FINDTEXTFULL = 2196;
constexpr int SCI_FORMATRANGE = 2151;
constexpr int SCI_FORMATRANGEFULL = 2777;
constexpr int SC_CHANGE_HISTORY_DISABLED = 0;
constexpr int SC_CHANGE_HISTORY_ENABLED = 1;
constexpr int SC_CHANGE_HISTORY_MARKERS = 2;
constexpr int SC_CHANGE_HISTORY_INDICATORS = 4;
constexpr int SCI_SETCHANGEHISTORY = 2780;
constexpr int SCI_GETCHANGEHISTORY = 2781;
constexpr int SCI_GETFIRSTVISIBLELINE = 2152;
constexpr int SCI_GETLINE = 2153;
constexpr int SCI_GETLINECOUNT = 2154;
constexpr int SCI_ALLOCATELINES = 2089;
constexpr int SCI_SETMARGINLEFT = 2155;
constexpr int SCI_GETMARGINLEFT = 2156;
constexpr int SCI_SETMARGINRIGHT = 2157;
constexpr int SCI_GETMARGINRIGHT = 2158;
constexpr int SCI_GETMODIFY = 2159;
constexpr int SCI_SETSEL = 2160;
constexpr int SCI_GETSELTEXT = 2161;
constexpr int SCI_GETTEXTRANGE = 2162;
constexpr int SCI_GETTEXTRANGEFULL = 2039;
constexpr int SCI_HIDESELECTION = 2163;
constexpr int SCI_GETSELECTIONHIDDEN = 2088;
constexpr int SCI_POINTXFROMPOSITION = 2164;
constexpr int SCI_POINTYFROMPOSITION = 2165;
constexpr int SCI_LINEFROMPOSITION = 2166;
constexpr int SCI_POSITIONFROMLINE = 2167;
constexpr int SCI_LINESCROLL = 2168;
constexpr int SCI_SCROLLCARET = 2169;
constexpr int SCI_SCROLLRANGE = 2569;
constexpr int SCI_REPLACESEL = 2170;
constexpr int SCI_SETREADONLY = 2171;
constexpr int SCI_NULL = 2172;
constexpr int SCI_CANPASTE = 2173;
constexpr int SCI_CANUNDO = 2174;
constexpr int SCI_EMPTYUNDOBUFFER = 2175;
constexpr int SCI_UNDO = 2176;
constexpr int SCI_CUT = 2177;
constexpr int SCI_COPY = 2178;
constexpr int SCI_PASTE = 2179;
constexpr int SCI_CLEAR = 2180;
constexpr int SCI_SETTEXT = 2181;
constexpr int SCI_GETTEXT = 2182;
constexpr int SCI_GETTEXTLENGTH = 2183;
constexpr int SCI_GETDIRECTFUNCTION = 2184;
constexpr int SCI_GETDIRECTSTATUSFUNCTION = 2772;
constexpr int SCI_GETDIRECTPOINTER = 2185;
constexpr int SCI_SETOVERTYPE = 2186;
constexpr int SCI_GETOVERTYPE = 2187;
constexpr int SCI_SETCARETWIDTH = 2188;
constexpr int SCI_GETCARETWIDTH = 2189;
constexpr int SCI_SETTARGETSTART = 2190;
constexpr int SCI_GETTARGETSTART = 2191;
constexpr int SCI_SETTARGETSTARTVIRTUALSPACE = 2728;
constexpr int SCI_GETTARGETSTARTVIRTUALSPACE = 2729;
constexpr int SCI_SETTARGETEND = 2192;
constexpr int SCI_GETTARGETEND = 2193;
constexpr int SCI_SETTARGETENDVIRTUALSPACE = 2730;
constexpr int SCI_GETTARGETENDVIRTUALSPACE = 2731;
constexpr int SCI_SETTARGETRANGE = 2686;
constexpr int SCI_GETTARGETTEXT = 2687;
constexpr int SCI_TARGETFROMSELECTION = 2287;
constexpr int SCI_TARGETWHOLEDOCUMENT = 2690;
constexpr int SCI_REPLACETARGET = 2194;
constexpr int SCI_REPLACETARGETRE = 2195;
constexpr int SCI_SEARCHINTARGET = 2197;
constexpr int SCI_SETSEARCHFLAGS = 2198;
constexpr int SCI_GETSEARCHFLAGS = 2199;
constexpr int SCI_CALLTIPSHOW = 2200;
constexpr int SCI_CALLTIPCANCEL = 2201;
constexpr int SCI_CALLTIPACTIVE = 2202;
constexpr int SCI_CALLTIPPOSSTART = 2203;
constexpr int SCI_CALLTIPSETPOSSTART = 2214;
constexpr int SCI_CALLTIPSETHLT = 2204;
constexpr int SCI_CALLTIPSETBACK = 2205;
constexpr int SCI_CALLTIPSETFORE = 2206;
constexpr int SCI_CALLTIPSETFOREHLT = 2207;
constexpr int SCI_CALLTIPUSESTYLE = 2212;
constexpr int SCI_CALLTIPSETPOSITION = 2213;
constexpr int SCI_VISIBLEFROMDOCLINE = 2220;
constexpr int SCI_DOCLINEFROMVISIBLE = 2221;
constexpr int SCI_WRAPCOUNT = 2235;
constexpr int SC_FOLDLEVELNONE = 0x0;
constexpr int SC_FOLDLEVELBASE = 0x400;
constexpr int SC_FOLDLEVELWHITEFLAG = 0x1000;
constexpr int SC_FOLDLEVELHEADERFLAG = 0x2000;
constexpr int SC_FOLDLEVELNUMBERMASK = 0x0FFF;
constexpr int SCI_SETFOLDLEVEL = 2222;
constexpr int SCI_GETFOLDLEVEL = 2223;
constexpr int SCI_GETLASTCHILD = 2224;
constexpr int SCI_GETFOLDPARENT = 2225;
constexpr int SCI_SHOWLINES = 2226;
constexpr int SCI_HIDELINES = 2227;
constexpr int SCI_GETLINEVISIBLE = 2228;
constexpr int SCI_GETALLLINESVISIBLE = 2236;
constexpr int SCI_SETFOLDEXPANDED = 2229;
constexpr int SCI_GETFOLDEXPANDED = 2230;
constexpr int SCI_TOGGLEFOLD = 2231;
constexpr int SCI_TOGGLEFOLDSHOWTEXT = 2700;
constexpr int SC_FOLDDISPLAYTEXT_HIDDEN = 0;
constexpr int SC_FOLDDISPLAYTEXT_STANDARD = 1;
constexpr int SC_FOLDDISPLAYTEXT_BOXED = 2;
constexpr int SCI_FOLDDISPLAYTEXTSETSTYLE = 2701;
constexpr int SCI_FOLDDISPLAYTEXTGETSTYLE = 2707;
constexpr int SCI_SETDEFAULTFOLDDISPLAYTEXT = 2722;
constexpr int SCI_GETDEFAULTFOLDDISPLAYTEXT = 2723;
constexpr int SC_FOLDACTION_CONTRACT = 0;
constexpr int SC_FOLDACTION_EXPAND = 1;
constexpr int SC_FOLDACTION_TOGGLE = 2;
constexpr int SC_FOLDACTION_CONTRACT_EVERY_LEVEL = 4;
constexpr int SCI_FOLDLINE = 2237;
constexpr int SCI_FOLDCHILDREN = 2238;
constexpr int SCI_EXPANDCHILDREN = 2239;
constexpr int SCI_FOLDALL = 2662;
constexpr int SCI_ENSUREVISIBLE = 2232;
constexpr int SC_AUTOMATICFOLD_NONE = 0x0000;
constexpr int SC_AUTOMATICFOLD_SHOW = 0x0001;
constexpr int SC_AUTOMATICFOLD_CLICK = 0x0002;
constexpr int SC_AUTOMATICFOLD_CHANGE = 0x0004;
constexpr int SCI_SETAUTOMATICFOLD = 2663;
constexpr int SCI_GETAUTOMATICFOLD = 2664;
constexpr int SC_FOLDFLAG_NONE = 0x0000;
constexpr int SC_FOLDFLAG_LINEBEFORE_EXPANDED = 0x0002;
constexpr int SC_FOLDFLAG_LINEBEFORE_CONTRACTED = 0x0004;
constexpr int SC_FOLDFLAG_LINEAFTER_EXPANDED = 0x0008;
constexpr int SC_FOLDFLAG_LINEAFTER_CONTRACTED = 0x0010;
constexpr int SC_FOLDFLAG_LEVELNUMBERS = 0x0040;
constexpr int SC_FOLDFLAG_LINESTATE = 0x0080;
constexpr int SCI_SETFOLDFLAGS = 2233;
constexpr int SCI_ENSUREVISIBLEENFORCEPOLICY = 2234;
constexpr int SCI_SETTABINDENTS = 2260;
constexpr int SCI_GETTABINDENTS = 2261;
constexpr int SCI_SETBACKSPACEUNINDENTS = 2262;
constexpr int SCI_GETBACKSPACEUNINDENTS = 2263;
constexpr int SC_TIME_FOREVER = 10000000;
constexpr int SCI_SETMOUSEDWELLTIME = 2264;
constexpr int SCI_GETMOUSEDWELLTIME = 2265;
constexpr int SCI_WORDSTARTPOSITION = 2266;
constexpr int SCI_WORDENDPOSITION = 2267;
constexpr int SCI_ISRANGEWORD = 2691;
constexpr int SC_IDLESTYLING_NONE = 0;
constexpr int SC_IDLESTYLING_TOVISIBLE = 1;
constexpr int SC_IDLESTYLING_AFTERVISIBLE = 2;
constexpr int SC_IDLESTYLING_ALL = 3;
constexpr int SCI_SETIDLESTYLING = 2692;
constexpr int SCI_GETIDLESTYLING = 2693;
constexpr int SC_WRAP_NONE = 0;
constexpr int SC_WRAP_WORD = 1;
constexpr int SC_WRAP_CHAR = 2;
constexpr int SC_WRAP_WHITESPACE = 3;
constexpr int SCI_SETWRAPMODE = 2268;
constexpr int SCI_GETWRAPMODE = 2269;
constexpr int SC_WRAPVISUALFLAG_NONE = 0x0000;
constexpr int SC_WRAPVISUALFLAG_END = 0x0001;
constexpr int SC_WRAPVISUALFLAG_START = 0x0002;
constexpr int SC_WRAPVISUALFLAG_MARGIN = 0x0004;
constexpr int SCI_SETWRAPVISUALFLAGS = 2460;
constexpr int SCI_GETWRAPVISUALFLAGS = 2461;
constexpr int SC_WRAPVISUALFLAGLOC_DEFAULT = 0x0000;
constexpr int SC_WRAPVISUALFLAGLOC_END_BY_TEXT = 0x0001;
constexpr int SC_WRAPVISUALFLAGLOC_START_BY_TEXT = 0x0002;
constexpr int SCI_SETWRAPVISUALFLAGSLOCATION = 2462;
constexpr int SCI_GETWRAPVISUALFLAGSLOCATION = 2463;
constexpr int SCI_SETWRAPSTARTINDENT = 2464;
constexpr int SCI_GETWRAPSTARTINDENT = 2465;
constexpr int SC_WRAPINDENT_FIXED = 0;
constexpr int SC_WRAPINDENT_SAME = 1;
constexpr int SC_WRAPINDENT_INDENT = 2;
constexpr int SC_WRAPINDENT_DEEPINDENT = 3;
constexpr int SCI_SETWRAPINDENTMODE = 2472;
constexpr int SCI_GETWRAPINDENTMODE = 2473;
constexpr int SC_CACHE_NONE = 0;
constexpr int SC_CACHE_CARET = 1;
constexpr int SC_CACHE_PAGE = 2;
constexpr int SC_CACHE_DOCUMENT = 3;
constexpr int SCI_SETLAYOUTCACHE = 2272;
constexpr int SCI_GETLAYOUTCACHE = 2273;
constexpr int SCI_SETSCROLLWIDTH = 2274;
constexpr int SCI_GETSCROLLWIDTH = 2275;
constexpr int SCI_SETSCROLLWIDTHTRACKING = 2516;
constexpr int SCI_GETSCROLLWIDTHTRACKING = 2517;
constexpr int SCI_TEXTWIDTH = 2276;
constexpr int SCI_SETENDATLASTLINE = 2277;
constexpr int SCI_GETENDATLASTLINE = 2278;
constexpr int SCI_TEXTHEIGHT = 2279;
constexpr int SCI_SETVSCROLLBAR = 2280;
constexpr int SCI_GETVSCROLLBAR = 2281;
constexpr int SCI_APPENDTEXT = 2282;
constexpr int SCI_APPENDSTYLEDTEXT = 2298;
constexpr int SCI_INSERTSTYLEDTEXT = 2299;
constexpr int SC_PHASES_ONE = 0;
constexpr int SC_PHASES_TWO = 1;
constexpr int SC_PHASES_MULTIPLE = 2;
constexpr int SCI_GETPHASESDRAW = 2673;
constexpr int SCI_SETPHASESDRAW = 2674;
constexpr int SC_EFF_QUALITY_MASK = 0xF;
constexpr int SC_EFF_QUALITY_DEFAULT = 0;
constexpr int SC_EFF_QUALITY_NON_ANTIALIASED = 1;
constexpr int SC_EFF_QUALITY_ANTIALIASED = 2;
constexpr int SC_EFF_QUALITY_LCD_OPTIMIZED = 3;
constexpr int SCI_SETFONTQUALITY = 2611;
constexpr int SCI_GETFONTQUALITY = 2612;
constexpr int SCI_SETFIRSTVISIBLELINE = 2613;
constexpr int SC_MULTIPASTE_ONCE = 0;
constexpr int SC_MULTIPASTE_EACH = 1;
constexpr int SCI_SETMULTIPASTE = 2614;
constexpr int SCI_GETMULTIPASTE = 2615;
constexpr int SCI_GETTAG = 2616;
constexpr int SCI_LINESJOIN = 2288;
constexpr int SCI_LINESSPLIT = 2289;
constexpr int SCI_SETFOLDMARGINCOLOUR = 2290;
constexpr int SCI_SETFOLDMARGINHICOLOUR = 2291;
constexpr int SC_ACCESSIBILITY_DISABLED = 0;
constexpr int SC_ACCESSIBILITY_ENABLED = 1;
constexpr int SCI_SETACCESSIBILITY = 2702;
constexpr int SCI_GETACCESSIBILITY = 2703;
constexpr int SCI_LINEDOWN = 2300;
constexpr int SCI_LINEDOWNEXTEND = 2301;
constexpr int SCI_LINEUP = 2302;
constexpr int SCI_LINEUPEXTEND = 2303;
constexpr int SCI_CHARLEFT = 2304;
constexpr int SCI_CHARLEFTEXTEND = 2305;
constexpr int SCI_CHARRIGHT = 2306;
constexpr int SCI_CHARRIGHTEXTEND = 2307;
constexpr int SCI_WORDLEFT = 2308;
constexpr int SCI_WORDLEFTEXTEND = 2309;
constexpr int SCI_WORDRIGHT = 2310;
constexpr int SCI_WORDRIGHTEXTEND = 2311;
constexpr int SCI_HOME = 2312;
constexpr int SCI_HOMEEXTEND = 2313;
constexpr int SCI_LINEEND = 2314;
constexpr int SCI_LINEENDEXTEND = 2315;
constexpr int SCI_DOCUMENTSTART = 2316;
constexpr int SCI_DOCUMENTSTARTEXTEND = 2317;
constexpr int SCI_DOCUMENTEND = 2318;
constexpr int SCI_DOCUMENTENDEXTEND = 2319;
constexpr int SCI_PAGEUP = 2320;
constexpr int SCI_PAGEUPEXTEND = 2321;
constexpr int SCI_PAGEDOWN = 2322;
constexpr int SCI_PAGEDOWNEXTEND = 2323;
constexpr int SCI_EDITTOGGLEOVERTYPE = 2324;
constexpr int SCI_CANCEL = 2325;
constexpr int SCI_DELETEBACK = 2326;
constexpr int SCI_TAB = 2327;
constexpr int SCI_BACKTAB = 2328;
constexpr int SCI_NEWLINE = 2329;
constexpr int SCI_FORMFEED = 2330;
constexpr int SCI_VCHOME = 2331;
constexpr int SCI_VCHOMEEXTEND = 2332;
constexpr int SCI_ZOOMIN = 2333;
constexpr int SCI_ZOOMOUT = 2334;
constexpr int SCI_DELWORDLEFT = 2335;
constexpr int SCI_DELWORDRIGHT = 2336;
constexpr int SCI_DELWORDRIGHTEND = 2518;
constexpr int SCI_LINECUT = 2337;
constexpr int SCI_LINEDELETE = 2338;
constexpr int SCI_LINETRANSPOSE = 2339;
constexpr int SCI_LINEREVERSE = 2354;
constexpr int SCI_LINEDUPLICATE = 2404;
constexpr int SCI_LOWERCASE = 2340;
constexpr int SCI_UPPERCASE = 2341;
constexpr int SCI_LINESCROLLDOWN = 2342;
constexpr int SCI_LINESCROLLUP = 2343;
constexpr int SCI_DELETEBACKNOTLINE = 2344;
constexpr int SCI_HOMEDISPLAY = 2345;
constexpr int SCI_HOMEDISPLAYEXTEND = 2346;
constexpr int SCI_LINEENDDISPLAY = 2347;
constexpr int SCI_LINEENDDISPLAYEXTEND = 2348;
constexpr int SCI_HOMEWRAP = 2349;
constexpr int SCI_HOMEWRAPEXTEND = 2450;
constexpr int SCI_LINEENDWRAP = 2451;
constexpr int SCI_LINEENDWRAPEXTEND = 2452;
constexpr int SCI_VCHOMEWRAP = 2453;
constexpr int SCI_VCHOMEWRAPEXTEND = 2454;
constexpr int SCI_LINECOPY = 2455;
constexpr int SCI_MOVECARETINSIDEVIEW = 2401;
constexpr int SCI_LINELENGTH = 2350;
constexpr int SCI_BRACEHIGHLIGHT = 2351;
constexpr int SCI_BRACEHIGHLIGHTINDICATOR = 2498;
constexpr int SCI_BRACEBADLIGHT = 2352;
constexpr int SCI_BRACEBADLIGHTINDICATOR = 2499;
constexpr int SCI_BRACEMATCH = 2353;
constexpr int SCI_BRACEMATCHNEXT = 2369;
constexpr int SCI_GETVIEWEOL = 2355;
constexpr int SCI_SETVIEWEOL = 2356;
constexpr int SCI_GETDOCPOINTER = 2357;
constexpr int SCI_SETDOCPOINTER = 2358;
constexpr int SCI_SETMODEVENTMASK = 2359;
constexpr int EDGE_NONE = 0;
constexpr int EDGE_LINE = 1;
constexpr int EDGE_BACKGROUND = 2;
constexpr int EDGE_MULTILINE = 3;
constexpr int SCI_GETEDGECOLUMN = 2360;
constexpr int SCI_SETEDGECOLUMN = 2361;
constexpr int SCI_GETEDGEMODE = 2362;
constexpr int SCI_SETEDGEMODE = 2363;
constexpr int SCI_GETEDGECOLOUR = 2364;
constexpr int SCI_SETEDGECOLOUR = 2365;
constexpr int SCI_MULTIEDGEADDLINE = 2694;
constexpr int SCI_MULTIEDGECLEARALL = 2695;
constexpr int SCI_GETMULTIEDGECOLUMN = 2749;
constexpr int SCI_SEARCHANCHOR = 2366;
constexpr int SCI_SEARCHNEXT = 2367;
constexpr int SCI_SEARCHPREV = 2368;
constexpr int SCI_LINESONSCREEN = 2370;
constexpr int SC_POPUP_NEVER = 0;
constexpr int SC_POPUP_ALL = 1;
constexpr int SC_POPUP_TEXT = 2;
constexpr int SCI_USEPOPUP = 2371;
constexpr int SCI_SELECTIONISRECTANGLE = 2372;
constexpr int SCI_SETZOOM = 2373;
constexpr int SCI_GETZOOM = 2374;
constexpr int SC_DOCUMENTOPTION_DEFAULT = 0;
constexpr int SC_DOCUMENTOPTION_STYLES_NONE = 0x1;
constexpr int SC_DOCUMENTOPTION_TEXT_LARGE = 0x100;
constexpr int SCI_CREATEDOCUMENT = 2375;
constexpr int SCI_ADDREFDOCUMENT = 2376;
constexpr int SCI_RELEASEDOCUMENT = 2377;
constexpr int SCI_GETDOCUMENTOPTIONS = 2379;
constexpr int SCI_GETMODEVENTMASK = 2378;
constexpr int SCI_SETCOMMANDEVENTS = 2717;
constexpr int SCI_GETCOMMANDEVENTS = 2718;
constexpr int SCI_SETFOCUS = 2380;
constexpr int SCI_GETFOCUS = 2381;
constexpr int SC_STATUS_OK = 0;
constexpr int SC_STATUS_FAILURE = 1;
constexpr int SC_STATUS_BADALLOC = 2;
constexpr int SC_STATUS_WARN_START = 1000;
constexpr int SC_STATUS_WARN_REGEX = 1001;
constexpr int SCI_SETSTATUS = 2382;
constexpr int SCI_GETSTATUS = 2383;
constexpr int SCI_SETMOUSEDOWNCAPTURES = 2384;
constexpr int SCI_GETMOUSEDOWNCAPTURES = 2385;
constexpr int SCI_SETMOUSEWHEELCAPTURES = 2696;
constexpr int SCI_GETMOUSEWHEELCAPTURES = 2697;
constexpr int SCI_SETCURSOR = 2386;
constexpr int SCI_GETCURSOR = 2387;
constexpr int SCI_SETCONTROLCHARSYMBOL = 2388;
constexpr int SCI_GETCONTROLCHARSYMBOL = 2389;
constexpr int SCI_WORDPARTLEFT = 2390;
constexpr int SCI_WORDPARTLEFTEXTEND = 2391;
constexpr int SCI_WORDPARTRIGHT = 2392;
constexpr int SCI_WORDPARTRIGHTEXTEND = 2393;
constexpr int VISIBLE_SLOP = 0x01;
constexpr int VISIBLE_STRICT = 0x04;
constexpr int SCI_SETVISIBLEPOLICY = 2394;
constexpr int SCI_DELLINELEFT = 2395;
constexpr int SCI_DELLINERIGHT = 2396;
constexpr int SCI_SETXOFFSET = 2397;
constexpr int SCI_GETXOFFSET = 2398;
constexpr int SCI_CHOOSECARETX = 2399;
constexpr int SCI_GRABFOCUS = 2400;
constexpr int CARET_SLOP = 0x01;
constexpr int CARET_STRICT = 0x04;
constexpr int CARET_JUMPS = 0x10;
constexpr int CARET_EVEN = 0x08;
constexpr int SCI_SETXCARETPOLICY = 2402;
constexpr int SCI_SETYCARETPOLICY = 2403;
constexpr int SCI_SETPRINTWRAPMODE = 2406;
constexpr int SCI_GETPRINTWRAPMODE = 2407;
constexpr int SCI_SETHOTSPOTACTIVEFORE = 2410;
constexpr int SCI_GETHOTSPOTACTIVEFORE = 2494;
constexpr int SCI_SETHOTSPOTACTIVEBACK = 2411;
constexpr int SCI_GETHOTSPOTACTIVEBACK = 2495;
constexpr int SCI_SETHOTSPOTACTIVEUNDERLINE = 2412;
constexpr int SCI_GETHOTSPOTACTIVEUNDERLINE = 2496;
constexpr int SCI_SETHOTSPOTSINGLELINE = 2421;
constexpr int SCI_GETHOTSPOTSINGLELINE = 2497;
constexpr int SCI_PARADOWN = 2413;
constexpr int SCI_PARADOWNEXTEND = 2414;
constexpr int SCI_PARAUP = 2415;
constexpr int SCI_PARAUPEXTEND = 2416;
constexpr int SCI_POSITIONBEFORE = 2417;
constexpr int SCI_POSITIONAFTER = 2418;
constexpr int SCI_POSITIONRELATIVE = 2670;
constexpr int SCI_POSITIONRELATIVECODEUNITS = 2716;
constexpr int SCI_COPYRANGE = 2419;
constexpr int SCI_COPYTEXT = 2420;
constexpr int SC_SEL_STREAM = 0;
constexpr int SC_SEL_RECTANGLE = 1;
constexpr int SC_SEL_LINES = 2;
constexpr int SC_SEL_THIN = 3;
constexpr int SCI_SETSELECTIONMODE = 2422;
constexpr int SCI_GETSELECTIONMODE = 2423;
constexpr int SCI_GETMOVEEXTENDSSELECTION = 2706;
constexpr int SCI_GETLINESELSTARTPOSITION = 2424;
constexpr int SCI_GETLINESELENDPOSITION = 2425;
constexpr int SCI_LINEDOWNRECTEXTEND = 2426;
constexpr int SCI_LINEUPRECTEXTEND = 2427;
constexpr int SCI_CHARLEFTRECTEXTEND = 2428;
constexpr int SCI_CHARRIGHTRECTEXTEND = 2429;
constexpr int SCI_HOMERECTEXTEND = 2430;
constexpr int SCI_VCHOMERECTEXTEND = 2431;
constexpr int SCI_LINEENDRECTEXTEND = 2432;
constexpr int SCI_PAGEUPRECTEXTEND = 2433;
constexpr int SCI_PAGEDOWNRECTEXTEND = 2434;
constexpr int SCI_STUTTEREDPAGEUP = 2435;
constexpr int SCI_STUTTEREDPAGEUPEXTEND = 2436;
constexpr int SCI_STUTTEREDPAGEDOWN = 2437;
constexpr int SCI_STUTTEREDPAGEDOWNEXTEND = 2438;
constexpr int SCI_WORDLEFTEND = 2439;
constexpr int SCI_WORDLEFTENDEXTEND = 2440;
constexpr int SCI_WORDRIGHTEND = 2441;
constexpr int SCI_WORDRIGHTENDEXTEND = 2442;
constexpr int SCI_SETWHITESPACECHARS = 2443;
constexpr int SCI_GETWHITESPACECHARS = 2647;
constexpr int SCI_SETPUNCTUATIONCHARS = 2648;
constexpr int SCI_GETPUNCTUATIONCHARS = 2649;
constexpr int SCI_SETCHARSDEFAULT = 2444;
constexpr int SCI_AUTOCGETCURRENT = 2445;
constexpr int SCI_AUTOCGETCURRENTTEXT = 2610;
constexpr int SC_CASEINSENSITIVEBEHAVIOUR_RESPECTCASE = 0;
constexpr int SC_CASEINSENSITIVEBEHAVIOUR_IGNORECASE = 1;
constexpr int SCI_AUTOCSETCASEINSENSITIVEBEHAVIOUR = 2634;
constexpr int SCI_AUTOCGETCASEINSENSITIVEBEHAVIOUR = 2635;
constexpr int SC_MULTIAUTOC_ONCE = 0;
constexpr int SC_MULTIAUTOC_EACH = 1;
constexpr int SCI_AUTOCSETMULTI = 2636;
constexpr int SCI_AUTOCGETMULTI = 2637;
constexpr int SC_ORDER_PRESORTED = 0;
constexpr int SC_ORDER_PERFORMSORT = 1;
constexpr int SC_ORDER_CUSTOM = 2;
constexpr int SCI_AUTOCSETORDER = 2660;
constexpr int SCI_AUTOCGETORDER = 2661;
constexpr int SCI_ALLOCATE = 2446;
constexpr int SCI_TARGETASUTF8 = 2447;
constexpr int SCI_SETLENGTHFORENCODE = 2448;
constexpr int SCI_ENCODEDFROMUTF8 = 2449;
constexpr int SCI_FINDCOLUMN = 2456;
constexpr int SC_CARETSTICKY_OFF = 0;
constexpr int SC_CARETSTICKY_ON = 1;
constexpr int SC_CARETSTICKY_WHITESPACE = 2;
constexpr int SCI_GETCARETSTICKY = 2457;
constexpr int SCI_SETCARETSTICKY = 2458;
constexpr int SCI_TOGGLECARETSTICKY = 2459;
constexpr int SCI_SETPASTECONVERTENDINGS = 2467;
constexpr int SCI_GETPASTECONVERTENDINGS = 2468;
constexpr int SCI_REPLACERECTANGULAR = 2771;
constexpr int SCI_SELECTIONDUPLICATE = 2469;
constexpr int SCI_SETCARETLINEBACKALPHA = 2470;
constexpr int SCI_GETCARETLINEBACKALPHA = 2471;
constexpr int CARETSTYLE_INVISIBLE = 0;
constexpr int CARETSTYLE_LINE = 1;
constexpr int CARETSTYLE_BLOCK = 2;
constexpr int CARETSTYLE_OVERSTRIKE_BAR = 0;
constexpr int CARETSTYLE_OVERSTRIKE_BLOCK = 0x10;
constexpr int CARETSTYLE_CURSES = 0x20;
constexpr int CARETSTYLE_INS_MASK = 0xF;
constexpr int CARETSTYLE_BLOCK_AFTER = 0x100;
constexpr int SCI_SETCARETSTYLE = 2512;
constexpr int SCI_GETCARETSTYLE = 2513;
constexpr int SCI_SETINDICATORCURRENT = 2500;
constexpr int SCI_GETINDICATORCURRENT = 2501;
constexpr int SCI_SETINDICATORVALUE = 2502;
constexpr int SCI_GETINDICATORVALUE = 2503;
constexpr int SCI_INDICATORFILLRANGE = 2504;
constexpr int SCI_INDICATORCLEARRANGE = 2505;
constexpr int SCI_INDICATORALLONFOR = 2506;
constexpr int SCI_INDICATORVALUEAT = 2507;
constexpr int SCI_INDICATORSTART = 2508;
constexpr int SCI_INDICATOREND = 2509;
constexpr int SCI_SETPOSITIONCACHE = 2514;
constexpr int SCI_GETPOSITIONCACHE = 2515;
constexpr int SCI_SETLAYOUTTHREADS = 2775;
constexpr int SCI_GETLAYOUTTHREADS = 2776;
constexpr int SCI_COPYALLOWLINE = 2519;
constexpr int SCI_GETCHARACTERPOINTER = 2520;
constexpr int SCI_GETRANGEPOINTER = 2643;
constexpr int SCI_GETGAPPOSITION = 2644;
constexpr int SCI_INDICSETALPHA = 2523;
constexpr int SCI_INDICGETALPHA = 2524;
constexpr int SCI_INDICSETOUTLINEALPHA = 2558;
constexpr int SCI_INDICGETOUTLINEALPHA = 2559;
constexpr int SCI_SETEXTRAASCENT = 2525;
constexpr int SCI_GETEXTRAASCENT = 2526;
constexpr int SCI_SETEXTRADESCENT = 2527;
constexpr int SCI_GETEXTRADESCENT = 2528;
constexpr int SCI_MARKERSYMBOLDEFINED = 2529;
constexpr int SCI_MARGINSETTEXT = 2530;
constexpr int SCI_MARGINGETTEXT = 2531;
constexpr int SCI_MARGINSETSTYLE = 2532;
constexpr int SCI_MARGINGETSTYLE = 2533;
constexpr int SCI_MARGINSETSTYLES = 2534;
constexpr int SCI_MARGINGETSTYLES = 2535;
constexpr int SCI_MARGINTEXTCLEARALL = 2536;
constexpr int SCI_MARGINSETSTYLEOFFSET = 2537;
constexpr int SCI_MARGINGETSTYLEOFFSET = 2538;
constexpr int SC_MARGINOPTION_NONE = 0;
constexpr int SC_MARGINOPTION_SUBLINESELECT = 1;
constexpr int SCI_SETMARGINOPTIONS = 2539;
constexpr int SCI_GETMARGINOPTIONS = 2557;
constexpr int SCI_ANNOTATIONSETTEXT = 2540;
constexpr int SCI_ANNOTATIONGETTEXT = 2541;
constexpr int SCI_ANNOTATIONSETSTYLE = 2542;
constexpr int SCI_ANNOTATIONGETSTYLE = 2543;
constexpr int SCI_ANNOTATIONSETSTYLES = 2544;
constexpr int SCI_ANNOTATIONGETSTYLES = 2545;
constexpr int SCI_ANNOTATIONGETLINES = 2546;
constexpr int SCI_ANNOTATIONCLEARALL = 2547;
constexpr int ANNOTATION_HIDDEN = 0;
constexpr int ANNOTATION_STANDARD = 1;
constexpr int ANNOTATION_BOXED = 2;
constexpr int ANNOTATION_INDENTED = 3;
constexpr int SCI_ANNOTATIONSETVISIBLE = 2548;
constexpr int SCI_ANNOTATIONGETVISIBLE = 2549;
constexpr int SCI_ANNOTATIONSETSTYLEOFFSET = 2550;
constexpr int SCI_ANNOTATIONGETSTYLEOFFSET = 2551;
constexpr int SCI_RELEASEALLEXTENDEDSTYLES = 2552;
constexpr int SCI_ALLOCATEEXTENDEDSTYLES = 2553;
constexpr int UNDO_NONE = 0;
constexpr int UNDO_MAY_COALESCE = 1;
constexpr int SCI_ADDUNDOACTION = 2560;
constexpr int SCI_CHARPOSITIONFROMPOINT = 2561;
constexpr int SCI_CHARPOSITIONFROMPOINTCLOSE = 2562;
constexpr int SCI_SETMOUSESELECTIONRECTANGULARSWITCH = 2668;
constexpr int SCI_GETMOUSESELECTIONRECTANGULARSWITCH = 2669;
constexpr int SCI_SETMULTIPLESELECTION = 2563;
constexpr int SCI_GETMULTIPLESELECTION = 2564;
constexpr int SCI_SETADDITIONALSELECTIONTYPING = 2565;
constexpr int SCI_GETADDITIONALSELECTIONTYPING = 2566;
constexpr int SCI_SETADDITIONALCARETSBLINK = 2567;
constexpr int SCI_GETADDITIONALCARETSBLINK = 2568;
constexpr int SCI_SETADDITIONALCARETSVISIBLE = 2608;
constexpr int SCI_GETADDITIONALCARETSVISIBLE = 2609;
constexpr int SCI_GETSELECTIONS = 2570;
constexpr int SCI_GETSELECTIONEMPTY = 2650;
constexpr int SCI_CLEARSELECTIONS = 2571;
constexpr int SCI_SETSELECTION = 2572;
constexpr int SCI_ADDSELECTION = 2573;
constexpr int SCI_DROPSELECTIONN = 2671;
constexpr int SCI_SETMAINSELECTION = 2574;
constexpr int SCI_GETMAINSELECTION = 2575;
constexpr int SCI_SETSELECTIONNCARET = 2576;
constexpr int SCI_GETSELECTIONNCARET = 2577;
constexpr int SCI_SETSELECTIONNANCHOR = 2578;
constexpr int SCI_GETSELECTIONNANCHOR = 2579;
constexpr int SCI_SETSELECTIONNCARETVIRTUALSPACE = 2580;
constexpr int SCI_GETSELECTIONNCARETVIRTUALSPACE = 2581;
constexpr int SCI_SETSELECTIONNANCHORVIRTUALSPACE = 2582;
constexpr int SCI_GETSELECTIONNANCHORVIRTUALSPACE = 2583;
constexpr int SCI_SETSELECTIONNSTART = 2584;
constexpr int SCI_GETSELECTIONNSTART = 2585;
constexpr int SCI_GETSELECTIONNSTARTVIRTUALSPACE = 2726;
constexpr int SCI_SETSELECTIONNEND = 2586;
constexpr int SCI_GETSELECTIONNENDVIRTUALSPACE = 2727;
constexpr int SCI_GETSELECTIONNEND = 2587;
constexpr int SCI_SETRECTANGULARSELECTIONCARET = 2588;
constexpr int SCI_GETRECTANGULARSELECTIONCARET = 2589;
constexpr int SCI_SETRECTANGULARSELECTIONANCHOR = 2590;
constexpr int SCI_GETRECTANGULARSELECTIONANCHOR = 2591;
constexpr int SCI_SETRECTANGULARSELECTIONCARETVIRTUALSPACE = 2592;
constexpr int SCI_GETRECTANGULARSELECTIONCARETVIRTUALSPACE = 2593;
constexpr int SCI_SETRECTANGULARSELECTIONANCHORVIRTUALSPACE = 2594;
constexpr int SCI_GETRECTANGULARSELECTIONANCHORVIRTUALSPACE = 2595;
constexpr int SCVS_NONE = 0;
constexpr int SCVS_RECTANGULARSELECTION = 1;
constexpr int SCVS_USERACCESSIBLE = 2;
constexpr int SCVS_NOWRAPLINESTART = 4;
constexpr int SCI_SETVIRTUALSPACEOPTIONS = 2596;
constexpr int SCI_GETVIRTUALSPACEOPTIONS = 2597;
constexpr int SCI_SETRECTANGULARSELECTIONMODIFIER = 2598;
constexpr int SCI_GETRECTANGULARSELECTIONMODIFIER = 2599;
constexpr int SCI_SETADDITIONALSELFORE = 2600;
constexpr int SCI_SETADDITIONALSELBACK = 2601;
constexpr int SCI_SETADDITIONALSELALPHA = 2602;
constexpr int SCI_GETADDITIONALSELALPHA = 2603;
constexpr int SCI_SETADDITIONALCARETFORE = 2604;
constexpr int SCI_GETADDITIONALCARETFORE = 2605;
constexpr int SCI_ROTATESELECTION = 2606;
constexpr int SCI_SWAPMAINANCHORCARET = 2607;
constexpr int SCI_MULTIPLESELECTADDNEXT = 2688;
constexpr int SCI_MULTIPLESELECTADDEACH = 2689;
constexpr int SCI_CHANGELEXERSTATE = 2617;
constexpr int SCI_CONTRACTEDFOLDNEXT = 2618;
constexpr int SCI_VERTICALCENTRECARET = 2619;
constexpr int SCI_MOVESELECTEDLINESUP = 2620;
constexpr int SCI_MOVESELECTEDLINESDOWN = 2621;
constexpr int SCI_SETIDENTIFIER = 2622;
constexpr int SCI_GETIDENTIFIER = 2623;
constexpr int SCI_RGBAIMAGESETWIDTH = 2624;
constexpr int SCI_RGBAIMAGESETHEIGHT = 2625;
constexpr int SCI_RGBAIMAGESETSCALE = 2651;
constexpr int SCI_MARKERDEFINERGBAIMAGE = 2626;
constexpr int SCI_REGISTERRGBAIMAGE = 2627;
constexpr int SCI_SCROLLTOSTART = 2628;
constexpr int SCI_SCROLLTOEND = 2629;
constexpr int SC_TECHNOLOGY_DEFAULT = 0;
constexpr int SC_TECHNOLOGY_DIRECTWRITE = 1;
constexpr int SC_TECHNOLOGY_DIRECTWRITERETAIN = 2;
constexpr int SC_TECHNOLOGY_DIRECTWRITEDC = 3;
constexpr int SCI_SETTECHNOLOGY = 2630;
constexpr int SCI_GETTECHNOLOGY = 2631;
constexpr int SCI_CREATELOADER = 2632;
constexpr int SCI_FINDINDICATORSHOW = 2640;
constexpr int SCI_FINDINDICATORFLASH = 2641;
constexpr int SCI_FINDINDICATORHIDE = 2642;
constexpr int SCI_VCHOMEDISPLAY = 2652;
constexpr int SCI_VCHOMEDISPLAYEXTEND = 2653;
constexpr int SCI_GETCARETLINEVISIBLEALWAYS = 2654;
constexpr int SCI_SETCARETLINEVISIBLEALWAYS = 2655;
constexpr int SC_LINE_END_TYPE_DEFAULT = 0;
constexpr int SC_LINE_END_TYPE_UNICODE = 1;
constexpr int SCI_SETLINEENDTYPESALLOWED = 2656;
constexpr int SCI_GETLINEENDTYPESALLOWED = 2657;
constexpr int SCI_GETLINEENDTYPESACTIVE = 2658;
constexpr int SCI_SETREPRESENTATION = 2665;
constexpr int SCI_GETREPRESENTATION = 2666;
constexpr int SCI_CLEARREPRESENTATION = 2667;
constexpr int SCI_CLEARALLREPRESENTATIONS = 2770;
constexpr int SC_REPRESENTATION_PLAIN = 0;
constexpr int SC_REPRESENTATION_BLOB = 1;
constexpr int SC_REPRESENTATION_COLOUR = 0x10;
constexpr int SCI_SETREPRESENTATIONAPPEARANCE = 2766;
constexpr int SCI_GETREPRESENTATIONAPPEARANCE = 2767;
constexpr int SCI_SETREPRESENTATIONCOLOUR = 2768;
constexpr int SCI_GETREPRESENTATIONCOLOUR = 2769;
constexpr int SCI_EOLANNOTATIONSETTEXT = 2740;
constexpr int SCI_EOLANNOTATIONGETTEXT = 2741;
constexpr int SCI_EOLANNOTATIONSETSTYLE = 2742;
constexpr int SCI_EOLANNOTATIONGETSTYLE = 2743;
constexpr int SCI_EOLANNOTATIONCLEARALL = 2744;
constexpr int EOLANNOTATION_HIDDEN = 0x0;
constexpr int EOLANNOTATION_STANDARD = 0x1;
constexpr int EOLANNOTATION_BOXED = 0x2;
constexpr int EOLANNOTATION_STADIUM = 0x100;
constexpr int EOLANNOTATION_FLAT_CIRCLE = 0x101;
constexpr int EOLANNOTATION_ANGLE_CIRCLE = 0x102;
constexpr int EOLANNOTATION_CIRCLE_FLAT = 0x110;
constexpr int EOLANNOTATION_FLATS = 0x111;
constexpr int EOLANNOTATION_ANGLE_FLAT = 0x112;
constexpr int EOLANNOTATION_CIRCLE_ANGLE = 0x120;
constexpr int EOLANNOTATION_FLAT_ANGLE = 0x121;
constexpr int EOLANNOTATION_ANGLES = 0x122;
constexpr int SCI_EOLANNOTATIONSETVISIBLE = 2745;
constexpr int SCI_EOLANNOTATIONGETVISIBLE = 2746;
constexpr int SCI_EOLANNOTATIONSETSTYLEOFFSET = 2747;
constexpr int SCI_EOLANNOTATIONGETSTYLEOFFSET = 2748;
constexpr int SC_SUPPORTS_LINE_DRAWS_FINAL = 0;
constexpr int SC_SUPPORTS_PIXEL_DIVISIONS = 1;
constexpr int SC_SUPPORTS_FRACTIONAL_STROKE_WIDTH = 2;
constexpr int SC_SUPPORTS_TRANSLUCENT_STROKE = 3;
constexpr int SC_SUPPORTS_PIXEL_MODIFICATION = 4;
constexpr int SC_SUPPORTS_THREAD_SAFE_MEASURE_WIDTHS = 5;
constexpr int SCI_SUPPORTSFEATURE = 2750;
constexpr int SC_LINECHARACTERINDEX_NONE = 0;
constexpr int SC_LINECHARACTERINDEX_UTF32 = 1;
constexpr int SC_LINECHARACTERINDEX_UTF16 = 2;
constexpr int SCI_GETLINECHARACTERINDEX = 2710;
constexpr int SCI_ALLOCATELINECHARACTERINDEX = 2711;
constexpr int SCI_RELEASELINECHARACTERINDEX = 2712;
constexpr int SCI_LINEFROMINDEXPOSITION = 2713;
constexpr int SCI_INDEXPOSITIONFROMLINE = 2714;
constexpr int SCI_STARTRECORD = 3001;
constexpr int SCI_STOPRECORD = 3002;
constexpr int SCI_SETLEXER = 4001;
constexpr int SCI_GETLEXER = 4002;
constexpr int SCI_COLOURISE = 4003;
constexpr int SCI_SETPROPERTY = 4004;
constexpr int KEYWORDSET_MAX = 8;
constexpr int SCI_SETKEYWORDS = 4005;
constexpr int SCI_SETLEXERLANGUAGE = 4006;
constexpr int SCI_GETPROPERTY = 4008;
constexpr int SCI_GETPROPERTYEXPANDED = 4009;
constexpr int SCI_GETPROPERTYINT = 4010;
constexpr int SCI_GETLEXERLANGUAGE = 4012;
constexpr int SCI_PRIVATELEXERCALL = 4013;
constexpr int SCI_PROPERTYNAMES = 4014;
constexpr int SC_TYPE_BOOLEAN = 0;
constexpr int SC_TYPE_INTEGER = 1;
constexpr int SC_TYPE_STRING = 2;
constexpr int SCI_PROPERTYTYPE = 4015;
constexpr int SCI_DESCRIBEPROPERTY = 4016;
constexpr int SCI_DESCRIBEKEYWORDSETS = 4017;
constexpr int SCI_GETLINEENDTYPESSUPPORTED = 4018;
constexpr int SCI_ALLOCATESUBSTYLES = 4020;
constexpr int SCI_GETSUBSTYLESSTART = 4021;
constexpr int SCI_GETSUBSTYLESLENGTH = 4022;
constexpr int SCI_GETSTYLEFROMSUBSTYLE = 4027;
constexpr int SCI_GETPRIMARYSTYLEFROMSTYLE = 4028;
constexpr int SCI_FREESUBSTYLES = 4023;
constexpr int SCI_SETIDENTIFIERS = 4024;
constexpr int SCI_DISTANCETOSECONDARYSTYLES = 4025;
constexpr int SCI_GETSUBSTYLEBASES = 4026;
constexpr int SCI_GETNAMEDSTYLES = 4029;
constexpr int SCI_NAMEOFSTYLE = 4030;
constexpr int SCI_TAGSOFSTYLE = 4031;
constexpr int SCI_DESCRIPTIONOFSTYLE = 4032;
constexpr int SCI_SETILEXER = 4033;
constexpr int SC_MOD_NONE = 0x0;
constexpr int SC_MOD_INSERTTEXT = 0x1;
constexpr int SC_MOD_DELETETEXT = 0x2;
constexpr int SC_MOD_CHANGESTYLE = 0x4;
constexpr int SC_MOD_CHANGEFOLD = 0x8;
constexpr int SC_PERFORMED_USER = 0x10;
constexpr int SC_PERFORMED_UNDO = 0x20;
constexpr int SC_PERFORMED_REDO = 0x40;
constexpr int SC_MULTISTEPUNDOREDO = 0x80;
constexpr int SC_LASTSTEPINUNDOREDO = 0x100;
constexpr int SC_MOD_CHANGEMARKER = 0x200;
constexpr int SC_MOD_BEFOREINSERT = 0x400;
constexpr int SC_MOD_BEFOREDELETE = 0x800;
constexpr int SC_MULTILINEUNDOREDO = 0x1000;
constexpr int SC_STARTACTION = 0x2000;
constexpr int SC_MOD_CHANGEINDICATOR = 0x4000;
constexpr int SC_MOD_CHANGELINESTATE = 0x8000;
constexpr int SC_MOD_CHANGEMARGIN = 0x10000;
constexpr int SC_MOD_CHANGEANNOTATION = 0x20000;
constexpr int SC_MOD_CONTAINER = 0x40000;
constexpr int SC_MOD_LEXERSTATE = 0x80000;
constexpr int SC_MOD_INSERTCHECK = 0x100000;
constexpr int SC_MOD_CHANGETABSTOPS = 0x200000;
constexpr int SC_MOD_CHANGEEOLANNOTATION = 0x400000;
constexpr int SC_MODEVENTMASKALL = 0x7FFFFF;
constexpr int SC_UPDATE_NONE = 0x0;
constexpr int SC_UPDATE_CONTENT = 0x1;
constexpr int SC_UPDATE_SELECTION = 0x2;
constexpr int SC_UPDATE_V_SCROLL = 0x4;
constexpr int SC_UPDATE_H_SCROLL = 0x8;
constexpr int SCEN_CHANGE = 768;
constexpr int SCEN_SETFOCUS = 512;
constexpr int SCEN_KILLFOCUS = 256;
constexpr int SCK_DOWN = 300;
constexpr int SCK_UP = 301;
constexpr int SCK_LEFT = 302;
constexpr int SCK_RIGHT = 303;
constexpr int SCK_HOME = 304;
constexpr int SCK_END = 305;
constexpr int SCK_PRIOR = 306;
constexpr int SCK_NEXT = 307;
constexpr int SCK_DELETE = 308;
constexpr int SCK_INSERT = 309;
constexpr int SCK_ESCAPE = 7;
constexpr int SCK_BACK = 8;
constexpr int SCK_TAB = 9;
constexpr int SCK_RETURN = 13;
constexpr int SCK_ADD = 310;
constexpr int SCK_SUBTRACT = 311;
constexpr int SCK_DIVIDE = 312;
constexpr int SCK_WIN = 313;
constexpr int SCK_RWIN = 314;
constexpr int SCK_MENU = 315;
constexpr int SCMOD_NORM = 0;
constexpr int SCMOD_SHIFT = 1;
constexpr int SCMOD_CTRL = 2;
constexpr int SCMOD_ALT = 4;
constexpr int SCMOD_SUPER = 8;
constexpr int SCMOD_META = 16;
constexpr int SC_AC_FILLUP = 1;
constexpr int SC_AC_DOUBLECLICK = 2;
constexpr int SC_AC_TAB = 3;
constexpr int SC_AC_NEWLINE = 4;
constexpr int SC_AC_COMMAND = 5;
constexpr int SC_CHARACTERSOURCE_DIRECT_INPUT = 0;
constexpr int SC_CHARACTERSOURCE_TENTATIVE_INPUT = 1;
constexpr int SC_CHARACTERSOURCE_IME_RESULT = 2;
constexpr int SCN_STYLENEEDED = 2000;
constexpr int SCN_CHARADDED = 2001;
constexpr int SCN_SAVEPOINTREACHED = 2002;
constexpr int SCN_SAVEPOINTLEFT = 2003;
constexpr int SCN_MODIFYATTEMPTRO = 2004;
constexpr int SCN_KEY = 2005;
constexpr int SCN_DOUBLECLICK = 2006;
constexpr int SCN_UPDATEUI = 2007;
constexpr int SCN_MODIFIED = 2008;
constexpr int SCN_MACRORECORD = 2009;
constexpr int SCN_MARGINCLICK = 2010;
constexpr int SCN_NEEDSHOWN = 2011;
constexpr int SCN_PAINTED = 2013;
constexpr int SCN_USERLISTSELECTION = 2014;
constexpr int SCN_URIDROPPED = 2015;
constexpr int SCN_DWELLSTART = 2016;
constexpr int SCN_DWELLEND = 2017;
constexpr int SCN_ZOOM = 2018;
constexpr int SCN_HOTSPOTCLICK = 2019;
constexpr int SCN_HOTSPOTDOUBLECLICK = 2020;
constexpr int SCN_CALLTIPCLICK = 2021;
constexpr int SCN_AUTOCSELECTION = 2022;
constexpr int SCN_INDICATORCLICK = 2023;
constexpr int SCN_INDICATORRELEASE = 2024;
constexpr int SCN_AUTOCCANCELLED = 2025;
constexpr int SCN_AUTOCCHARDELETED = 2026;
constexpr int SCN_HOTSPOTRELEASECLICK = 2027;
constexpr int SCN_FOCUSIN = 2028;
constexpr int SCN_FOCUSOUT = 2029;
constexpr int SCN_AUTOCCOMPLETED = 2030;
constexpr int SCN_MARGINRIGHTCLICK = 2031;
constexpr int SCN_AUTOCSELECTIONCHANGE = 2032;
constexpr int SC_BIDIRECTIONAL_DISABLED = 0;
constexpr int SC_BIDIRECTIONAL_L2R = 1;
constexpr int SC_BIDIRECTIONAL_R2L = 2;
constexpr int SCI_GETBIDIRECTIONAL = 2708;
constexpr int SCI_SETBIDIRECTIONAL = 2709;
#pragma endregion
#pragma region SCI Enumerations
enum class EWhiteSpace
{
	Invisible = SCWS_INVISIBLE,
	Visiblealways = SCWS_VISIBLEALWAYS,
	Visibleafterindent = SCWS_VISIBLEAFTERINDENT,
	Visibleonlyinindent = SCWS_VISIBLEONLYININDENT,
};
enum class ETabDrawMode
{
	Longarrow = SCTD_LONGARROW,
	Strikeout = SCTD_STRIKEOUT,
};
enum class EEndOfLine
{
	Crlf = SC_EOL_CRLF,
	Cr = SC_EOL_CR,
	Lf = SC_EOL_LF,
};
enum class EIMEInteraction
{
	Windowed = SC_IME_WINDOWED,
	Inline = SC_IME_INLINE,
};
enum class EAlpha
{
	Transparent = SC_ALPHA_TRANSPARENT,
	Opaque = SC_ALPHA_OPAQUE,
	Noalpha = SC_ALPHA_NOALPHA,
};
enum class ECursorShape
{
	Normal = SC_CURSORNORMAL,
	Arrow = SC_CURSORARROW,
	Wait = SC_CURSORWAIT,
	Reversearrow = SC_CURSORREVERSEARROW,
};
enum class EMarkerSymbol
{
	Circle = SC_MARK_CIRCLE,
	Roundrect = SC_MARK_ROUNDRECT,
	Arrow = SC_MARK_ARROW,
	Smallrect = SC_MARK_SMALLRECT,
	Shortarrow = SC_MARK_SHORTARROW,
	Empty = SC_MARK_EMPTY,
	Arrowdown = SC_MARK_ARROWDOWN,
	Minus = SC_MARK_MINUS,
	Plus = SC_MARK_PLUS,
	Vline = SC_MARK_VLINE,
	Lcorner = SC_MARK_LCORNER,
	Tcorner = SC_MARK_TCORNER,
	Boxplus = SC_MARK_BOXPLUS,
	Boxplusconnected = SC_MARK_BOXPLUSCONNECTED,
	Boxminus = SC_MARK_BOXMINUS,
	Boxminusconnected = SC_MARK_BOXMINUSCONNECTED,
	Lcornercurve = SC_MARK_LCORNERCURVE,
	Tcornercurve = SC_MARK_TCORNERCURVE,
	Circleplus = SC_MARK_CIRCLEPLUS,
	Circleplusconnected = SC_MARK_CIRCLEPLUSCONNECTED,
	Circleminus = SC_MARK_CIRCLEMINUS,
	Circleminusconnected = SC_MARK_CIRCLEMINUSCONNECTED,
	Background = SC_MARK_BACKGROUND,
	Dotdotdot = SC_MARK_DOTDOTDOT,
	Arrows = SC_MARK_ARROWS,
	Pixmap = SC_MARK_PIXMAP,
	Fullrect = SC_MARK_FULLRECT,
	Leftrect = SC_MARK_LEFTRECT,
	Available = SC_MARK_AVAILABLE,
	Underline = SC_MARK_UNDERLINE,
	Rgbaimage = SC_MARK_RGBAIMAGE,
	Bookmark = SC_MARK_BOOKMARK,
	Verticalbookmark = SC_MARK_VERTICALBOOKMARK,
	Bar = SC_MARK_BAR,
	Character = SC_MARK_CHARACTER,
};
enum class EMarkerOutline
{
	History_reverted_to_origin = SC_MARKNUM_HISTORY_REVERTED_TO_ORIGIN,
	History_saved = SC_MARKNUM_HISTORY_SAVED,
	History_modified = SC_MARKNUM_HISTORY_MODIFIED,
	History_reverted_to_modified = SC_MARKNUM_HISTORY_REVERTED_TO_MODIFIED,
	Folderend = SC_MARKNUM_FOLDEREND,
	Folderopenmid = SC_MARKNUM_FOLDEROPENMID,
	Foldermidtail = SC_MARKNUM_FOLDERMIDTAIL,
	Foldertail = SC_MARKNUM_FOLDERTAIL,
	Foldersub = SC_MARKNUM_FOLDERSUB,
	Folder = SC_MARKNUM_FOLDER,
	Folderopen = SC_MARKNUM_FOLDEROPEN,
};
enum class EMarginType
{
	Symbol = SC_MARGIN_SYMBOL,
	Number = SC_MARGIN_NUMBER,
	Back = SC_MARGIN_BACK,
	Fore = SC_MARGIN_FORE,
	Text = SC_MARGIN_TEXT,
	Rtext = SC_MARGIN_RTEXT,
	Colour = SC_MARGIN_COLOUR,
};
enum class EStylesCommon
{
	Default = STYLE_DEFAULT,
	Linenumber = STYLE_LINENUMBER,
	Bracelight = STYLE_BRACELIGHT,
	Bracebad = STYLE_BRACEBAD,
	Controlchar = STYLE_CONTROLCHAR,
	Indentguide = STYLE_INDENTGUIDE,
	Calltip = STYLE_CALLTIP,
	Folddisplaytext = STYLE_FOLDDISPLAYTEXT,
	Lastpredefined = STYLE_LASTPREDEFINED,
	Max = STYLE_MAX,
};
enum class ECharacterSet
{
	Ansi = SC_CHARSET_ANSI,
	Default = SC_CHARSET_DEFAULT,
	Baltic = SC_CHARSET_BALTIC,
	Chinesebig5 = SC_CHARSET_CHINESEBIG5,
	Easteurope = SC_CHARSET_EASTEUROPE,
	Gb2312 = SC_CHARSET_GB2312,
	Greek = SC_CHARSET_GREEK,
	Hangul = SC_CHARSET_HANGUL,
	Mac = SC_CHARSET_MAC,
	Oem = SC_CHARSET_OEM,
	Russian = SC_CHARSET_RUSSIAN,
	Oem866 = SC_CHARSET_OEM866,
	Cyrillic = SC_CHARSET_CYRILLIC,
	Shiftjis = SC_CHARSET_SHIFTJIS,
	Symbol = SC_CHARSET_SYMBOL,
	Turkish = SC_CHARSET_TURKISH,
	Johab = SC_CHARSET_JOHAB,
	Hebrew = SC_CHARSET_HEBREW,
	Arabic = SC_CHARSET_ARABIC,
	Vietnamese = SC_CHARSET_VIETNAMESE,
	Thai = SC_CHARSET_THAI,
	_8859_15 = SC_CHARSET_8859_15,
};
enum class ECaseVisible
{
	Mixed = SC_CASE_MIXED,
	Upper = SC_CASE_UPPER,
	Lower = SC_CASE_LOWER,
	Camel = SC_CASE_CAMEL,
};
enum class EFontWeight
{
	Normal = SC_WEIGHT_NORMAL,
	Semibold = SC_WEIGHT_SEMIBOLD,
	Bold = SC_WEIGHT_BOLD,
};
enum class EElement
{
	List = SC_ELEMENT_LIST,
	List_back = SC_ELEMENT_LIST_BACK,
	List_selected = SC_ELEMENT_LIST_SELECTED,
	List_selected_back = SC_ELEMENT_LIST_SELECTED_BACK,
	Selection_text = SC_ELEMENT_SELECTION_TEXT,
	Selection_back = SC_ELEMENT_SELECTION_BACK,
	Selection_additional_text = SC_ELEMENT_SELECTION_ADDITIONAL_TEXT,
	Selection_additional_back = SC_ELEMENT_SELECTION_ADDITIONAL_BACK,
	Selection_secondary_text = SC_ELEMENT_SELECTION_SECONDARY_TEXT,
	Selection_secondary_back = SC_ELEMENT_SELECTION_SECONDARY_BACK,
	Selection_inactive_text = SC_ELEMENT_SELECTION_INACTIVE_TEXT,
	Selection_inactive_back = SC_ELEMENT_SELECTION_INACTIVE_BACK,
	Caret = SC_ELEMENT_CARET,
	Caret_additional = SC_ELEMENT_CARET_ADDITIONAL,
	Caret_line_back = SC_ELEMENT_CARET_LINE_BACK,
	White_space = SC_ELEMENT_WHITE_SPACE,
	White_space_back = SC_ELEMENT_WHITE_SPACE_BACK,
	Hot_spot_active = SC_ELEMENT_HOT_SPOT_ACTIVE,
	Hot_spot_active_back = SC_ELEMENT_HOT_SPOT_ACTIVE_BACK,
	Fold_line = SC_ELEMENT_FOLD_LINE,
	Hidden_line = SC_ELEMENT_HIDDEN_LINE,
};
enum class ELayer
{
	Base = SC_LAYER_BASE,
	Under_text = SC_LAYER_UNDER_TEXT,
	Over_text = SC_LAYER_OVER_TEXT,
};
enum class EIndicatorStyle
{
	Plain = INDIC_PLAIN,
	Squiggle = INDIC_SQUIGGLE,
	Tt = INDIC_TT,
	Diagonal = INDIC_DIAGONAL,
	Strike = INDIC_STRIKE,
	Hidden = INDIC_HIDDEN,
	Box = INDIC_BOX,
	Roundbox = INDIC_ROUNDBOX,
	Straightbox = INDIC_STRAIGHTBOX,
	Dash = INDIC_DASH,
	Dots = INDIC_DOTS,
	Squigglelow = INDIC_SQUIGGLELOW,
	Dotbox = INDIC_DOTBOX,
	Squigglepixmap = INDIC_SQUIGGLEPIXMAP,
	Compositionthick = INDIC_COMPOSITIONTHICK,
	Compositionthin = INDIC_COMPOSITIONTHIN,
	Fullbox = INDIC_FULLBOX,
	Textfore = INDIC_TEXTFORE,
	Point = INDIC_POINT,
	Pointcharacter = INDIC_POINTCHARACTER,
	Gradient = INDIC_GRADIENT,
	Gradientcentre = INDIC_GRADIENTCENTRE,
	Point_top = INDIC_POINT_TOP,
	Container = INDIC_CONTAINER,
	Ime = INDIC_IME,
	Ime_max = INDIC_IME_MAX,
	Max = INDIC_MAX,
};
enum class EIndicatorNumbers
{
	Container = INDICATOR_CONTAINER,
	Ime = INDICATOR_IME,
	Ime_max = INDICATOR_IME_MAX,
	History_reverted_to_origin_insertion = INDICATOR_HISTORY_REVERTED_TO_ORIGIN_INSERTION,
	History_reverted_to_origin_deletion = INDICATOR_HISTORY_REVERTED_TO_ORIGIN_DELETION,
	History_saved_insertion = INDICATOR_HISTORY_SAVED_INSERTION,
	History_saved_deletion = INDICATOR_HISTORY_SAVED_DELETION,
	History_modified_insertion = INDICATOR_HISTORY_MODIFIED_INSERTION,
	History_modified_deletion = INDICATOR_HISTORY_MODIFIED_DELETION,
	History_reverted_to_modified_insertion = INDICATOR_HISTORY_REVERTED_TO_MODIFIED_INSERTION,
	History_reverted_to_modified_deletion = INDICATOR_HISTORY_REVERTED_TO_MODIFIED_DELETION,
	Max = INDICATOR_MAX,
};
enum class EIndicValue
{
	Bit = SC_INDICVALUEBIT,
	Mask = SC_INDICVALUEMASK,
};
enum class EIndicFlag
{
	None = SC_INDICFLAG_NONE,
	Valuefore = SC_INDICFLAG_VALUEFORE,
};
enum class EAutoCompleteOption
{
	Normal = SC_AUTOCOMPLETE_NORMAL,
	Fixed_size = SC_AUTOCOMPLETE_FIXED_SIZE,
};
enum class EIndentView
{
	None = SC_IV_NONE,
	Real = SC_IV_REAL,
	Lookforward = SC_IV_LOOKFORWARD,
	Lookboth = SC_IV_LOOKBOTH,
};
enum class EPrintOption
{
	Normal = SC_PRINT_NORMAL,
	Invertlight = SC_PRINT_INVERTLIGHT,
	Blackonwhite = SC_PRINT_BLACKONWHITE,
	Colouronwhite = SC_PRINT_COLOURONWHITE,
	Colouronwhitedefaultbg = SC_PRINT_COLOURONWHITEDEFAULTBG,
	Screencolours = SC_PRINT_SCREENCOLOURS,
};
enum class EFindOption
{
	None = SCFIND_NONE,
	Wholeword = SCFIND_WHOLEWORD,
	Matchcase = SCFIND_MATCHCASE,
	Wordstart = SCFIND_WORDSTART,
	Regexp = SCFIND_REGEXP,
	Posix = SCFIND_POSIX,
	Cxx11regex = SCFIND_CXX11REGEX,
};
enum class EChangeHistoryOption
{
	Disabled = SC_CHANGE_HISTORY_DISABLED,
	Enabled = SC_CHANGE_HISTORY_ENABLED,
	Markers = SC_CHANGE_HISTORY_MARKERS,
	Indicators = SC_CHANGE_HISTORY_INDICATORS,
};
enum class EFoldLevel
{
	None = SC_FOLDLEVELNONE,
	Base = SC_FOLDLEVELBASE,
	Whiteflag = SC_FOLDLEVELWHITEFLAG,
	Headerflag = SC_FOLDLEVELHEADERFLAG,
	Numbermask = SC_FOLDLEVELNUMBERMASK,
};
enum class EFoldDisplayTextStyle
{
	Hidden = SC_FOLDDISPLAYTEXT_HIDDEN,
	Standard = SC_FOLDDISPLAYTEXT_STANDARD,
	Boxed = SC_FOLDDISPLAYTEXT_BOXED,
};
enum class EFoldAction
{
	Contract = SC_FOLDACTION_CONTRACT,
	Expand = SC_FOLDACTION_EXPAND,
	Toggle = SC_FOLDACTION_TOGGLE,
	Contract_every_level = SC_FOLDACTION_CONTRACT_EVERY_LEVEL,
};
enum class EAutomaticFold
{
	None = SC_AUTOMATICFOLD_NONE,
	Show = SC_AUTOMATICFOLD_SHOW,
	Click = SC_AUTOMATICFOLD_CLICK,
	Change = SC_AUTOMATICFOLD_CHANGE,
};
enum class EFoldFlag
{
	None = SC_FOLDFLAG_NONE,
	Linebefore_expanded = SC_FOLDFLAG_LINEBEFORE_EXPANDED,
	Linebefore_contracted = SC_FOLDFLAG_LINEBEFORE_CONTRACTED,
	Lineafter_expanded = SC_FOLDFLAG_LINEAFTER_EXPANDED,
	Lineafter_contracted = SC_FOLDFLAG_LINEAFTER_CONTRACTED,
	Levelnumbers = SC_FOLDFLAG_LEVELNUMBERS,
	Linestate = SC_FOLDFLAG_LINESTATE,
};
enum class EIdleStyling
{
	None = SC_IDLESTYLING_NONE,
	Tovisible = SC_IDLESTYLING_TOVISIBLE,
	Aftervisible = SC_IDLESTYLING_AFTERVISIBLE,
	All = SC_IDLESTYLING_ALL,
};
enum class EWrap
{
	None = SC_WRAP_NONE,
	Word = SC_WRAP_WORD,
	Char = SC_WRAP_CHAR,
	Whitespace = SC_WRAP_WHITESPACE,
};
enum class EWrapVisualFlag
{
	None = SC_WRAPVISUALFLAG_NONE,
	End = SC_WRAPVISUALFLAG_END,
	Start = SC_WRAPVISUALFLAG_START,
	Margin = SC_WRAPVISUALFLAG_MARGIN,
};
enum class EWrapVisualLocation
{
	Default = SC_WRAPVISUALFLAGLOC_DEFAULT,
	End_by_text = SC_WRAPVISUALFLAGLOC_END_BY_TEXT,
	Start_by_text = SC_WRAPVISUALFLAGLOC_START_BY_TEXT,
};
enum class EWrapIndentMode
{
	Fixed = SC_WRAPINDENT_FIXED,
	Same = SC_WRAPINDENT_SAME,
	Indent = SC_WRAPINDENT_INDENT,
	Deepindent = SC_WRAPINDENT_DEEPINDENT,
};
enum class ELineCache
{
	None = SC_CACHE_NONE,
	Caret = SC_CACHE_CARET,
	Page = SC_CACHE_PAGE,
	Document = SC_CACHE_DOCUMENT,
};
enum class EPhasesDraw
{
	One = SC_PHASES_ONE,
	Two = SC_PHASES_TWO,
	Multiple = SC_PHASES_MULTIPLE,
};
enum class EFontQuality
{
	Quality_mask = SC_EFF_QUALITY_MASK,
	Quality_default = SC_EFF_QUALITY_DEFAULT,
	Quality_non_antialiased = SC_EFF_QUALITY_NON_ANTIALIASED,
	Quality_antialiased = SC_EFF_QUALITY_ANTIALIASED,
	Quality_lcd_optimized = SC_EFF_QUALITY_LCD_OPTIMIZED,
};
enum class EMultiPaste
{
	Once = SC_MULTIPASTE_ONCE,
	Each = SC_MULTIPASTE_EACH,
};
enum class EAccessibility
{
	Disabled = SC_ACCESSIBILITY_DISABLED,
	Enabled = SC_ACCESSIBILITY_ENABLED,
};
enum class EEdgeVisualStyle
{
	None = EDGE_NONE,
	Line = EDGE_LINE,
	Background = EDGE_BACKGROUND,
	Multiline = EDGE_MULTILINE,
};
enum class EPopUp
{
	Never = SC_POPUP_NEVER,
	All = SC_POPUP_ALL,
	Text = SC_POPUP_TEXT,
};
enum class EDocumentOption
{
	Default = SC_DOCUMENTOPTION_DEFAULT,
	Styles_none = SC_DOCUMENTOPTION_STYLES_NONE,
	Text_large = SC_DOCUMENTOPTION_TEXT_LARGE,
};
enum class EStatus
{
	Ok = SC_STATUS_OK,
	Failure = SC_STATUS_FAILURE,
	Badalloc = SC_STATUS_BADALLOC,
	Warn_start = SC_STATUS_WARN_START,
	Warn_regex = SC_STATUS_WARN_REGEX,
};
enum class EVisiblePolicy
{
	Slop = VISIBLE_SLOP,
	Strict = VISIBLE_STRICT,
};
enum class ECaretPolicy
{
	Slop = CARET_SLOP,
	Strict = CARET_STRICT,
	Jumps = CARET_JUMPS,
	Even = CARET_EVEN,
};
enum class ESelectionMode
{
	Stream = SC_SEL_STREAM,
	Rectangle = SC_SEL_RECTANGLE,
	Lines = SC_SEL_LINES,
	Thin = SC_SEL_THIN,
};
enum class ECaseInsensitiveBehaviour
{
	Respectcase = SC_CASEINSENSITIVEBEHAVIOUR_RESPECTCASE,
	Ignorecase = SC_CASEINSENSITIVEBEHAVIOUR_IGNORECASE,
};
enum class EMultiAutoComplete
{
	Once = SC_MULTIAUTOC_ONCE,
	Each = SC_MULTIAUTOC_EACH,
};
enum class EOrdering
{
	Presorted = SC_ORDER_PRESORTED,
	Performsort = SC_ORDER_PERFORMSORT,
	Custom = SC_ORDER_CUSTOM,
};
enum class ECaretSticky
{
	Off = SC_CARETSTICKY_OFF,
	On = SC_CARETSTICKY_ON,
	Whitespace = SC_CARETSTICKY_WHITESPACE,
};
enum class ECaretStyle
{
	Invisible = CARETSTYLE_INVISIBLE,
	Line = CARETSTYLE_LINE,
	Block = CARETSTYLE_BLOCK,
	Overstrike_bar = CARETSTYLE_OVERSTRIKE_BAR,
	Overstrike_block = CARETSTYLE_OVERSTRIKE_BLOCK,
	Curses = CARETSTYLE_CURSES,
	Ins_mask = CARETSTYLE_INS_MASK,
	Block_after = CARETSTYLE_BLOCK_AFTER,
};
enum class EMarginOption
{
	None = SC_MARGINOPTION_NONE,
	Sublineselect = SC_MARGINOPTION_SUBLINESELECT,
};
enum class EAnnotationVisible
{
	Hidden = ANNOTATION_HIDDEN,
	Standard = ANNOTATION_STANDARD,
	Boxed = ANNOTATION_BOXED,
	Indented = ANNOTATION_INDENTED,
};
enum class EUndoFlags
{
	None = UNDO_NONE,
	May_coalesce = UNDO_MAY_COALESCE,
};
enum class EVirtualSpace
{
	None = SCVS_NONE,
	Rectangularselection = SCVS_RECTANGULARSELECTION,
	Useraccessible = SCVS_USERACCESSIBLE,
	Nowraplinestart = SCVS_NOWRAPLINESTART,
};
enum class ETechnology
{
	Default = SC_TECHNOLOGY_DEFAULT,
	Directwrite = SC_TECHNOLOGY_DIRECTWRITE,
	Directwriteretain = SC_TECHNOLOGY_DIRECTWRITERETAIN,
	Directwritedc = SC_TECHNOLOGY_DIRECTWRITEDC,
};
enum class ELineEndType
{
	Default = SC_LINE_END_TYPE_DEFAULT,
	Unicode = SC_LINE_END_TYPE_UNICODE,
};
enum class ERepresentationAppearance
{
	__plain = SC_REPRESENTATION_PLAIN,
	__blob = SC_REPRESENTATION_BLOB,
	__colour = SC_REPRESENTATION_COLOUR,
};
enum class EEOLAnnotationVisible
{
	Hidden = EOLANNOTATION_HIDDEN,
	Standard = EOLANNOTATION_STANDARD,
	Boxed = EOLANNOTATION_BOXED,
	Stadium = EOLANNOTATION_STADIUM,
	Flat_circle = EOLANNOTATION_FLAT_CIRCLE,
	Angle_circle = EOLANNOTATION_ANGLE_CIRCLE,
	Circle_flat = EOLANNOTATION_CIRCLE_FLAT,
	Flats = EOLANNOTATION_FLATS,
	Angle_flat = EOLANNOTATION_ANGLE_FLAT,
	Circle_angle = EOLANNOTATION_CIRCLE_ANGLE,
	Flat_angle = EOLANNOTATION_FLAT_ANGLE,
	Angles = EOLANNOTATION_ANGLES,
};
enum class ESupports
{
	Line_draws_final = SC_SUPPORTS_LINE_DRAWS_FINAL,
	Pixel_divisions = SC_SUPPORTS_PIXEL_DIVISIONS,
	Fractional_stroke_width = SC_SUPPORTS_FRACTIONAL_STROKE_WIDTH,
	Translucent_stroke = SC_SUPPORTS_TRANSLUCENT_STROKE,
	Pixel_modification = SC_SUPPORTS_PIXEL_MODIFICATION,
	Thread_safe_measure_widths = SC_SUPPORTS_THREAD_SAFE_MEASURE_WIDTHS,
};
enum class ELineCharacterIndexType
{
	None = SC_LINECHARACTERINDEX_NONE,
	Utf32 = SC_LINECHARACTERINDEX_UTF32,
	Utf16 = SC_LINECHARACTERINDEX_UTF16,
};
enum class ETypeProperty
{
	Boolean = SC_TYPE_BOOLEAN,
	Integer = SC_TYPE_INTEGER,
	String = SC_TYPE_STRING,
};
enum class EModificationFlags
{
};
enum class EUpdate
{
	None = SC_UPDATE_NONE,
	Content = SC_UPDATE_CONTENT,
	Selection = SC_UPDATE_SELECTION,
	V_scroll = SC_UPDATE_V_SCROLL,
	H_scroll = SC_UPDATE_H_SCROLL,
};
enum class EFocusChange
{
	Change = SCEN_CHANGE,
	Setfocus = SCEN_SETFOCUS,
	Killfocus = SCEN_KILLFOCUS,
};
enum class EKeys
{
	Down = SCK_DOWN,
	Up = SCK_UP,
	Left = SCK_LEFT,
	Right = SCK_RIGHT,
	Home = SCK_HOME,
	End = SCK_END,
	Prior = SCK_PRIOR,
	Next = SCK_NEXT,
	Delete = SCK_DELETE,
	Insert = SCK_INSERT,
	Escape = SCK_ESCAPE,
	Back = SCK_BACK,
	Tab = SCK_TAB,
	Return = SCK_RETURN,
	Add = SCK_ADD,
	Subtract = SCK_SUBTRACT,
	Divide = SCK_DIVIDE,
	Win = SCK_WIN,
	Rwin = SCK_RWIN,
	Menu = SCK_MENU,
};
enum class EKeyMod
{
	Norm = SCMOD_NORM,
	Shift = SCMOD_SHIFT,
	Ctrl = SCMOD_CTRL,
	Alt = SCMOD_ALT,
	Super = SCMOD_SUPER,
	Meta = SCMOD_META,
};
enum class ECompletionMethods
{
	Fillup = SC_AC_FILLUP,
	Doubleclick = SC_AC_DOUBLECLICK,
	Tab = SC_AC_TAB,
	Newline = SC_AC_NEWLINE,
	Command = SC_AC_COMMAND,
};
enum class ECharacterSource
{
	Direct_input = SC_CHARACTERSOURCE_DIRECT_INPUT,
	Tentative_input = SC_CHARACTERSOURCE_TENTATIVE_INPUT,
	Ime_result = SC_CHARACTERSOURCE_IME_RESULT,
};
enum class EBidirectional
{
	Disabled = SC_BIDIRECTIONAL_DISABLED,
	L2r = SC_BIDIRECTIONAL_L2R,
	R2l = SC_BIDIRECTIONAL_R2L,
};
#pragma endregion
/* --Autogenerated -- end of section automatically generated from Scintilla.iface */

#endif

/* These structures are defined to be exactly the same shape as the Win32
 * CHARRANGE, TEXTRANGE, FINDTEXTEX, FORMATRANGE, and NMHDR structs.
 * So older code that treats Scintilla as a RichEdit will work. */

struct Sci_CharacterRange {
	Sci_PositionCR cpMin;
	Sci_PositionCR cpMax;
};

struct Sci_CharacterRangeFull {
	Sci_Position cpMin;
	Sci_Position cpMax;
};

struct Sci_TextRange {
	struct Sci_CharacterRange chrg;
	char *lpstrText;
};

struct Sci_TextRangeFull {
	struct Sci_CharacterRangeFull chrg;
	char *lpstrText;
};

struct Sci_TextToFind {
	struct Sci_CharacterRange chrg;
	const char *lpstrText;
	struct Sci_CharacterRange chrgText;
};

struct Sci_TextToFindFull {
	struct Sci_CharacterRangeFull chrg;
	const char *lpstrText;
	struct Sci_CharacterRangeFull chrgText;
};

typedef void *Sci_SurfaceID;

struct Sci_Rectangle {
	int left;
	int top;
	int right;
	int bottom;
};

/* This structure is used in printing and requires some of the graphics types
 * from Platform.h.  Not needed by most client code. */

struct Sci_RangeToFormat {
	Sci_SurfaceID hdc;
	Sci_SurfaceID hdcTarget;
	struct Sci_Rectangle rc;
	struct Sci_Rectangle rcPage;
	struct Sci_CharacterRange chrg;
};

struct Sci_RangeToFormatFull {
	Sci_SurfaceID hdc;
	Sci_SurfaceID hdcTarget;
	struct Sci_Rectangle rc;
	struct Sci_Rectangle rcPage;
	struct Sci_CharacterRangeFull chrg;
};

#ifndef __cplusplus
/* For the GTK+ platform, g-ir-scanner needs to have these typedefs. This
 * is not required in C++ code and actually seems to break ScintillaEditPy */
typedef struct Sci_NotifyHeader Sci_NotifyHeader;
typedef struct SCNotification SCNotification;
#endif

struct Sci_NotifyHeader {
	/* Compatible with Windows NMHDR.
	 * hwndFrom is really an environment specific window handle or pointer
	 * but most clients of Scintilla.h do not have this type visible. */
	void *hwndFrom;
	uptr_t idFrom;
	unsigned int code;
};

struct SCNotification {
	Sci_NotifyHeader nmhdr;
	Sci_Position position;
	/* SCN_STYLENEEDED, SCN_DOUBLECLICK, SCN_MODIFIED, SCN_MARGINCLICK, */
	/* SCN_NEEDSHOWN, SCN_DWELLSTART, SCN_DWELLEND, SCN_CALLTIPCLICK, */
	/* SCN_HOTSPOTCLICK, SCN_HOTSPOTDOUBLECLICK, SCN_HOTSPOTRELEASECLICK, */
	/* SCN_INDICATORCLICK, SCN_INDICATORRELEASE, */
	/* SCN_USERLISTSELECTION, SCN_AUTOCSELECTION */

	int ch;
	/* SCN_CHARADDED, SCN_KEY, SCN_AUTOCCOMPLETED, SCN_AUTOCSELECTION, */
	/* SCN_USERLISTSELECTION */
	int modifiers;
	/* SCN_KEY, SCN_DOUBLECLICK, SCN_HOTSPOTCLICK, SCN_HOTSPOTDOUBLECLICK, */
	/* SCN_HOTSPOTRELEASECLICK, SCN_INDICATORCLICK, SCN_INDICATORRELEASE, */

	int modificationType;	/* SCN_MODIFIED */
	const char *text;
	/* SCN_MODIFIED, SCN_USERLISTSELECTION, SCN_AUTOCSELECTION, SCN_URIDROPPED */

	Sci_Position length;		/* SCN_MODIFIED */
	Sci_Position linesAdded;	/* SCN_MODIFIED */
	int message;	/* SCN_MACRORECORD */
	uptr_t wParam;	/* SCN_MACRORECORD */
	sptr_t lParam;	/* SCN_MACRORECORD */
	Sci_Position line;		/* SCN_MODIFIED */
	int foldLevelNow;	/* SCN_MODIFIED */
	int foldLevelPrev;	/* SCN_MODIFIED */
	int margin;		/* SCN_MARGINCLICK */
	int listType;	/* SCN_USERLISTSELECTION */
	int x;			/* SCN_DWELLSTART, SCN_DWELLEND */
	int y;		/* SCN_DWELLSTART, SCN_DWELLEND */
	int token;		/* SCN_MODIFIED with SC_MOD_CONTAINER */
	Sci_Position annotationLinesAdded;	/* SCN_MODIFIED with SC_MOD_CHANGEANNOTATION */
	int updated;	/* SCN_UPDATEUI */
	int listCompletionMethod;
	/* SCN_AUTOCSELECTION, SCN_AUTOCCOMPLETED, SCN_USERLISTSELECTION, */
	int characterSource;	/* SCN_CHARADDED */
};

#ifdef INCLUDE_DEPRECATED_FEATURES

#define SCI_SETKEYSUNICODE 2521
#define SCI_GETKEYSUNICODE 2522

#define SCI_GETTWOPHASEDRAW 2283
#define SCI_SETTWOPHASEDRAW 2284

#define CharacterRange Sci_CharacterRange
#define TextRange Sci_TextRange
#define TextToFind Sci_TextToFind
#define RangeToFormat Sci_RangeToFormat
#define NotifyHeader Sci_NotifyHeader

#define SCI_SETSTYLEBITS 2090
#define SCI_GETSTYLEBITS 2091
#define SCI_GETSTYLEBITSNEEDED 4011

#define INDIC0_MASK 0x20
#define INDIC1_MASK 0x40
#define INDIC2_MASK 0x80
#define INDICS_MASK 0xE0

#endif

#endif
