#include "Q:\sdk\pr\pr\storage\sqlite.h"

	// Create sqlite table mapping meta data
			PR_SQLITE_TABLE(Record, "")
			//PR_SQLITE_COLUMN(Key        ,m_key        ,integer , "primary key autoincrement not null")
			//PR_SQLITE_COLUMN(Bool       ,m_bool       ,integer , "")
			//PR_SQLITE_COLUMN(Char       ,m_char       ,integer , "")
			//PR_SQLITE_COLUMN(Byte       ,m_byte       ,integer , "")
			//PR_SQLITE_COLUMN(Short      ,m_short      ,integer , "")
			//PR_SQLITE_COLUMN(Ushort     ,m_ushort     ,integer , "")
			//PR_SQLITE_COLUMN(Int        ,m_int        ,integer , "")
			//PR_SQLITE_COLUMN(Uint       ,m_uint       ,integer , "")
			//PR_SQLITE_COLUMN(Int64      ,m_int64      ,integer , "")
			//PR_SQLITE_COLUMN(Uint64     ,m_uint64     ,integer , "")
			//PR_SQLITE_COLUMN(Float      ,m_float      ,real    , "")
			//PR_SQLITE_COLUMN(Double     ,m_double     ,real    , "")
			PR_SQLITE_COLUMN(CharArray  ,m_char_array ,text    , "")
			//PR_SQLITE_COLUMN(IntArray   ,m_int_array  ,blob    , "")
			//PR_SQLITE_COL_AS(Enum       ,m_enum  ,int ,integer , "")
			//PR_SQLITE_COLUMN(String     ,m_string     ,text    , "")
			//PR_SQLITE_COLUMN(Buf        ,m_buf        ,blob    , "")
			//PR_SQLITE_COLUMN(EmptyBuf   ,m_empty_buf  ,blob    , "")
			PR_SQLITE_TABLE_END()